### ISSUE TITLE
MFC r365231: ixl(4): Add support for X710-T*L devices

### ISSUE THREAD

**Issue by 24fpsDaVinci** [opnsense/src#100]
Intel x710-t2l nic is not supported by if_ixl in opnsense. I had to compile latest driver from intel.

Software version used and hardware type:

OPNsense 21.1.r_1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD 
OpenSSL 1.1.1i 

Hardware:
Network Intel® x710-t2l

**Comment by fichtner** [comment]
7f999117637a
