### ISSUE TITLE
net: sfp: add workaround for Realtek RTL8672 and RTL9601C chips

### ISSUE THREAD

**Issue by xavo95** [opnsense/src#101]
So I was an owner of a CPGOS03-0490 v2.0 SFP ONT module, and while trying to use it, I faced some issues, as the card reported the module as not supported. Today I realized that Linux issued a patch to fix the modules.

- Could this be ported too?
- In order for the card to see the module show the driver be modified too?

> Workaround for GPON SFP modules based on VSOL V2801F brand was added in
commit 0d035bed2a4a ("net: sfp: VSOL V2801F / CarlitoxxPro CPGOS03-0490
v2.0 workaround"). But it works only for ids explicitly added to the list.
As there are more rebraded VSOL V2801F modules and OEM vendors are putting
into vendor name random strings we cannot build workaround based on ids.

Moreover issue which that commit tried to workaround is generic not only to
VSOL based modules, but rather to all GPON modules based on Realtek RTL8672
and RTL9601C chips.

They can be found for example in following GPON modules:
* V-SOL V2801F
* C-Data FD511GX-RM0
* OPTON GP801R
* BAUDCOM BD-1234-SFM
* CPGOS03-0490 v2.0
* Ubiquiti U-Fiber Instant
* EXOT EGS1

Those Realtek chips have broken EEPROM emulator which for N-byte read
operation returns just one byte of EEPROM data followed by N-1 zeros.

[Linux discussion](https://lore.kernel.org/netdev/20201230154755.14746-1-pali@kernel.org/)

[Linux branch with changes](https://git.kernel.org/pub/scm/linux/kernel/git/pali/linux.git/log/?h=sfp-rtl8672)

**Comment by fichtner** [comment]
We now have both the FreeBSD driver and the vendor driver in the hopes one will do what the other doesn't.
