### ISSUE TITLE
Traffic graph does not show the bandwidth of IPS enabled interfaces

### ISSUE THREAD

**Issue by JasMan78** [opnsense/src#103]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
The "Traffic Graph" does not show the current bandwidth of physical interfaces, on which IPS is enabled and no VLANs are configured. The table below the graph shows the correct bandwitdh.
As soon as I disable IPS (not IDS) or remove the affected interface from the IDS/IPS settings, the bandwidth is shown.

Physical interfaces, which have additional VLANs configured, are both shown correctly.

This happens since I've switched to a new hardware appliance with Intel network interfaces.
On my old hardware appliance with Realtek interfaces and the same IDS/IPS and VLAN configuration, the graph shows the bandwidth for all interfaces correctly.

I've found another user in the forum which is having the same issue (3): https://forum.opnsense.org/index.php?topic=18496.msg84177#msg84177

**To Reproduce**
1. Go to "Services: Intrusion Detection: Administration"
2. Enable IDS and IPS.
3. Add a physical interface which has no VLANs configured
4. Switch to the "Traffic graph"
5. As soon as all IDS/IPS rules are loaded, the bandwidth in the graph for the interface drops down to zero
6. The table at the bottom shows the correct current bandwidth

**Expected behavior**
No idea :)

**Screenshots**
![OPNsense - Trafficgraph Issue](https://user-images.githubusercontent.com/20991399/90443392-78a92780-e0dc-11ea-87d5-76f6985a0bc2.jpg)

**Relevant log files**
Please let me know if you need a log file to identify the issue.

**Environment**
OPNsense 20.7.1-amd64
Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 cores)/NRG IPU662
Networ Interfaces: Intel i211AT

**Comment by fichtner** [comment]
There is still some sort of issue here, reopen briefly to reassess https://forum.opnsense.org/index.php?topic=21168.0

**Comment by swhite2** [comment]
> There is still some sort of issue here, reopen briefly to reassess https://forum.opnsense.org/index.php?topic=21168.0

The fix related to the traffic graph in IPS-mode was related to Netmap-specific code in iflib. Users reporting new missing traffic counters (like the link mentioned above) in any interface mode should specify the NIC/driver in question, as many of them are not integrated with iflib. As such, the missing counters are often caused by developers not implementing the FreeBSD-specific counter mechanism. Whether this is true in all cases is unclear, as it is quite difficult to reproduce with the limited set of hardware available to me. Users should at least check if `netstat -idb [interface]` or `ifinfo [interface]` reports any in/out-bytes/packets. Should no bytes/packets be reported, the issue will be driver-related.

**Comment by Famaku** [comment]
Using Mellenox ConnectX-3 NICs (driver: mlx4en) this issue still exists. Oddly enough, this only affects setups in which VLANs are defined on virtual functions (i.e. VFs, see https://docs.google.com/spreadsheets/d/1RVj8K3XOzWi-Bkjq6hUxWudu7Cxd8FFTqjLiBMzZWEM/edit#gid=0). When VLANs are assigned in OPNSense (which has it's drawbacks compared to VFs), it works as intended. It would be great if anyone could have a look at this.

**Comment by fichtner** [comment]
mlx4en doesn't support native netmap which suggest the generic netmap driver does not support packet/byte accounting as well. At this point the accounting patch for iflib/netmap combination was added in FreeBSD not long ago, but I'm not sure if it should be our effort to address this other issue in the OS. Maybe @muratbalaban43 and team can help out on this one.

Cheers,
Franco

**Comment by Fl1pp3d0ff** [comment]
This is still an issue in 2026 since before 25.7.10

**Comment by fichtner** [comment]
It depends on the interface driver I guess. Emulated netmap mode should work.
