### ISSUE TITLE
growfs, backport https://reviews.freebsd.org/rS366187

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/src#106]
It seems I ran into the "BAD CHECK-HASH" issue, compiled a new version of growsf including https://github.com/freebsd/freebsd-src/commit/7d38c4af1773bf0278414e4cf60d540e0a280eb6 which seemed to have solved my issue. 

Although it's unlikely a lot of people run into this, maybe it's a good idea to backport the patch.

**Comment by fichtner** [comment]
It's in via https://github.com/opnsense/src/commit/532da928d6, probably best to pull into stable/21.1 for 21.1.3?

**Comment by AdSchellevis** [comment]
@fichtner you're being too kind here :) thanks!

**Comment by fichtner** [comment]
Ok to close?

**Comment by AdSchellevis** [comment]
oops, forgot :)
