### ISSUE TITLE
Virtualized transparent bridging OPNsense kernel panics in virtio-net

### ISSUE THREAD

**Issue by Ukko-Ylijumala** [opnsense/src#108]
- [ X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ X ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

OPNsense virtualized under Proxmox with virtio-net interfaces kernel panics intermittently under load. There are 5 vtnet devices in total - vtnet0 and vtnet1 are bridged together, vtnet2 is the pfsync device, and vtnet3 and vtnet4 are used for routing (WAN-LAN NAT and CARP). vtnet0 is bound to WAN side and vtnet1 to the LAN side (on the host); LAN side virtio_pci device is always the one which is implicated in the panics. The bridge does not have an IP address.

The actual network load does not seem to correlate strongly with the kernel panics. I can push ~700MB/s traffic through the bridge with iperf3 for quite some time and not generate a panic, but a light (~100Mbit) production load can cause a panic rather soon.

The panics are virtually identical on both hosts. Rarely one OPNsense crashes, then the second goes down literally seconds after the first. Booting the previous kernel does not solve the panics.

**To Reproduce**

Install OPNsense under Proxmox, machine type i440fx, CPU type EPYC-Rome. Configure 2 virtio network devices and bridge them together in OPNsense. Direct traffic through the transparent bridge which has some PF rules (it seems that simple pass all rules in addition to automatic rules are sufficient).

**Expected behavior**

Transparent bridging with virtio devices works without kernel panics.

**Describe alternatives you considered**

Changing virtual network interfaces to e1000 seems to not cause panics, but performance is abysmal. With net.isr.[max|num]threads=1 and non-multiqueue virtio-net devices the frequency of the panics is lessened greatly. Increasing net.isr threads and multiqueue to 8 increases the panic frequency to at least multiple panics a day.

**Relevant log files**

```
Fatal trap 12: page fault while in kernel mode
cpuid = 3; apic id = 03
fault virtual address   = 0x20
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff80d79b37
stack pointer           = 0x28:0xfffffe00028de460
frame pointer           = 0x28:0xfffffe00028de470
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = resume, IOPL = 0
current process         = 12 (irq282: virtio_pci3)
trap number             = 12
panic: page fault
cpuid = 3
time = 1614697396
__HardenedBSD_version = 1200059 __FreeBSD_version = 1201000
version = FreeBSD 12.1-RELEASE-p13-HBSD #0  5a415173060(stable/21.1)-dirty: Fri Feb  5 16:41:22 CET 2021
    root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe00028de110
vpanic() at vpanic+0x1a2/frame 0xfffffe00028de160
panic() at panic+0x43/frame 0xfffffe00028de1c0
trap_fatal() at trap_fatal+0x39c/frame 0xfffffe00028de220
trap_pfault() at trap_pfault+0x49/frame 0xfffffe00028de280
trap() at trap+0x29f/frame 0xfffffe00028de390
calltrap() at calltrap+0x8/frame 0xfffffe00028de390
--- trap 0xc, rip = 0xffffffff80d79b37, rsp = 0xfffffe00028de460, rbp = 0xfffffe00028de470 ---
turnstile_broadcast() at turnstile_broadcast+0x47/frame 0xfffffe00028de470
__mtx_unlock_sleep() at __mtx_unlock_sleep+0xb9/frame 0xfffffe00028de4a0
pf_test() at pf_test+0xbfc/frame 0xfffffe00028de640
pf_check_out() at pf_check_out+0x1d/frame 0xfffffe00028de660
pfil_run_hooks() at pfil_run_hooks+0x87/frame 0xfffffe00028de6f0
bridge_pfil() at bridge_pfil+0x2e1/frame 0xfffffe00028de770
bridge_forward() at bridge_forward+0x347/frame 0xfffffe00028de7d0
bridge_input() at bridge_input+0x40c/frame 0xfffffe00028de840
ether_nh_input() at ether_nh_input+0x209/frame 0xfffffe00028de8a0
netisr_dispatch_src() at netisr_dispatch_src+0xcf/frame 0xfffffe00028de8f0
ether_input() at ether_input+0x4b/frame 0xfffffe00028de920
vtnet_rxq_eof() at vtnet_rxq_eof+0x7cf/frame 0xfffffe00028de9e0
vtnet_rx_vq_intr() at vtnet_rx_vq_intr+0x71/frame 0xfffffe00028dea10
ithread_loop() at ithread_loop+0x1d4/frame 0xfffffe00028dea70
fork_exit() at fork_exit+0x83/frame 0xfffffe00028deab0
fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe00028deab0
--- trap 0, rip = 0, rsp = 0, rbp = 0 ---
KDB: enter: panic
```

**Additional context**

There are 2 physical Proxmox hosts, each running one identical OPNsense installation for redundancy (PFSYNC + CARP IPs). The hosts have redundant LACP bonds to dual 10GbE switches on both sides (WAN and LAN side). The whole switch setup is running RSPT (transparent bridges included) and the path costs favour the primary firewall. Path failover and RSTP port blocking work as intended, failover happens in less than 2 seconds on primary firewall failure. After reboot the paths fail back as intended.

**Environment**

OPNsense: 21.1.2-amd64 (OpenSSL), 8vCPUs, 8GB RAM
Proxmox hosts: AMD EPYC 7262 (Rome), 64GB RAM, Linux 5.4.78-2-pve
2x Intel 82599ES 10-Gigabit SFP+ (WAN)
2x Broadcom BCM57416 NetXtreme-E 10GBase-T (LAN)
Cisco 10GbE switches in 2x2 configuration (stacked), LACP bonds to both Proxmox hosts

**Comment by Ukko-Ylijumala** [comment]
> 2 problems, virtio is known to be mit the best in FreeBSD and also Bridges in FreeBSD are not that good. Best would be to reproduce with Vanilla BSD and report to upstream

How can I install a vanilla FreeBSD kernel in the OPNsense? I have tried to find instructions for that to no avail. Creating an identical FreeBSD VM will take quite some time (as I am not that well versed in FreeBSD inner workings these days) that I might not be able to spare.

**Comment by sempervictus** [comment]
@mimugmail - my virtio issue just got moved to this repo as well, could you possibly elaborate a bit on the known concerns with the setup?

**Comment by mimugmail** [comment]
I have no idea what you talk about, sorry. But regarding bridges it might be worth to test again with 22.1

**Comment by sempervictus** [comment]
> 2 problems, virtio is known to be mit the best in FreeBSD and also Bridges in FreeBSD are not that good. Best would be to reproduce with Vanilla BSD and report to upstream

When you say "known to be," i'm curious what the known problems are and if you could point me to the official upstream discussions on these issues so that i could figure out a bit better whats afoot in the magic land of BSD network drivers. 

Unfortunately my own issue is not with bridges, #135 is a bit more insidious and seems specific to the virtio network stack - so i'm more interested in that piece and how to make it work correctly again on existing machines (converting to q35 on the fly is apparently not possible, BSD fails to boot entirely or even see a boot drive).

**Comment by Ukko-Ylijumala** [comment]
@sempervictus This FreeBSD bug is probably relevant, if you haven't seen it yet: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=165059

**Comment by fichtner** [comment]
Closing with new FreeBSD version on top.

**Comment by sempervictus** [comment]
I just started the 22.1 upgrades, none in VM yet so not sure whether the underlying BSD upgrade actually addressed this.

**Comment by fichtner** [comment]
@sempervictus can always reopen although I don't want to drag this across multiple major versions... bugs.freebsd.org might be a better place to make noise

**Comment by sempervictus** [comment]
Ah, thanks - i just saw the other related notifications come through too.
