### ISSUE TITLE
Unable to detect Intel X722 NICS

### ISSUE THREAD

**Issue by alteredtech** [opnsense/src#112]
**Is your feature request related to a problem? Please describe.**
**A clear and concise description of what the problem is including your motivation for the request,**

I have recently purchased this [super micro server](https://www.supermicro.com/en/products/system/1U/1019/SYS-1019P-FHN2T.cfm). When installing, the Intel X722 NICs are not being detected/ the driver is not functioning properly.

**Describe the solution you like**
**A clear and concise description of what you want to happen.**

I would like to be able to install and have the kernel have or correctly use the right driver for my NICs. 

**Describe alternatives you considered**

Looked at this [post](https://forum.opnsense.org/index.php?topic=21447.0) about a broadcom 25GbE not being found but that is due to other drivers for broadcom. I tried to look for drivers for supermicro thinking it might be the same thing, but could not find it.

Then I downloaded the plugins/src/ports of OPNsense from git and transferred them to the machine to try and compile the driver myself but it seems that the if_ixl.ko is already on. Followed this [post](https://forum.opnsense.org/index.php?topic=21517.0) about doing that.

Additional context

When I run pciconf -lv I do not see the NICs show up at all.
When I run kldload if_ixl.ko I get this
```
interface ixl.3 already present in the kld 'kernel'!

linker_load_file: /boot/kernel/if_ixl.ko - unsupported file type
```
I looked in the kernel config and the ixl is built but I have zero ideas as to why it will not find them. 
Added if_ixl_load = "YES" to both loader.conf and loader.conf.local on separate reboots, neither found them.

**Comment by fichtner** [comment]
It's either in this bit for 21.7 or not yet in FreeBSD 12-STABLE... https://github.com/opnsense/src/commit/7f999117637a72b

**Comment by alteredtech** [comment]
Okay so just make sure I understood what you said. It should be in the 21.7 release or just has not been added to the freeBSD stable? is there a way to beta the 21.7?

**Comment by fichtner** [comment]
I don't know about X722 specifically, but there is a large driver update waiting for 21.7 to drop. I can provide a test kernel if you want.

As for X722 not included in this 21.7 update last time I checked FreeBSD 12-STABLE had no other updates so that makes efforts to support in OPNsense impossible.


Cheers,
Franco

**Comment by alteredtech** [comment]
So until FreeBSD 12-stable has it included, it is impossible to get the X722 working with OPNsense natively? Sorry for the dumb questions, haven't had to mess with this side of it until this issue. 
Do you have do links on how I could compile it myself into OPNsense since it already has the if_ixl installed and remove the old one? Since when I last did it, it just told me that it was already loaded and that its an unuspported file type (what I have in my original post)
I have this intel [post](https://downloadcenter.intel.com/download/25160/Ethernet-Intel-Network-Adapter-Driver-for-Intel-Ethernet-Controller-700-Series-under-FreeBSD-#:~:text=This%20release%20includes%20FreeBSD%20Base,based%20on%20the%20following%20controllers%3A&text=Intel%C2%AE%20Ethernet%20Network%20Connection%20X722) for freebsd x722 support but cant get past step 4 in the read me from previous explained issue.

**Comment by fichtner** [comment]
Test kernel is available via:

    # opnsense-update -kr 21.7.a_59
    # opnsense-shell reboot


Cheers,
Franco

**Comment by fichtner** [comment]
PS: corrected command via @mimugmail's report

**Comment by mimugmail** [comment]
The driver and NIC already works in 20.7, I also tested the kernel successfully but it also ran with 2.1.0 driver.
In my case I tried because I only got a link with 10G but not with an 1G GBIC, but from the datasheet it seems the X722 supports 10G-only

**Comment by fichtner** [comment]
Ok, time to close this then. Thanks!

**Comment by alteredtech** [comment]
I managed to get a usb ethernet adapter so I could get internet to the machine. I updated to the 21.7 and still no NICs were discovered. I have tried running proxmox, pfsense, standard freebsd and none of them were able to find the NICs. I am about to try centos 7 complete version to see if that can. And this might be a dumb question, do the NICs need to be plugged in for the kernel to discover them?

**Comment by fichtner** [comment]
You should try to compare to FreeBSD 12 to be sure. I can’t speak for pfSense.

Generally, if drivers are not in the kernel by default loading the module is enough, i.e.:

# kldload ixl


Cheers,
Franco

**Comment by alteredtech** [comment]
Could to clarify by what you mean by compare to FreeBSD 12? I have installed it to the server and met the same results. Looked at the kernel config on OPNsense and FreeBSD, they have the ixl being built. 
When I tried to load ixl, it says it is already loaded in the kernel.
I have also tried Centos 7 everything version and still didnt find it. At this point could the hardware be damaged?

**Comment by mimugmail** [comment]
Please check if it sits correctly in the riser card. Previously I had similar thing with an APU and Wifi card flowing around due to hard packaging.

**Comment by alteredtech** [comment]
There is no riser card, they are soldered to the board. This is [the server I got.](https://www.supermicro.com/en/products/system/1U/1019/SYS-1019P-FHN2T.cfm)
![IMG_5313](https://user-images.githubusercontent.com/61751327/114278403-f19f1b80-99ec-11eb-9abc-17872db20656.jpg)
![IMG_5312](https://user-images.githubusercontent.com/61751327/114278404-f532a280-99ec-11eb-81d3-d98fd8341938.jpg)

**Comment by alteredtech** [comment]
So would this be hardware or driver issue? Since there is no riser card to be dislodged from shipping and there are apparently the correct drivers for this chipset, the only other conclusion I can come to is that it is hardware. The lights flash when something is plugged in as if there is activity but it seems to be a pattern but I couldnt find anything on it. I am going to try a windows server 2019 install and see if that can see them.

**Comment by fichtner** [comment]
Thanks for the clarifications. It could ne a newer model that lacks support then. The FreeBSD system has a port with a newer ixl driver from Intel and you could try that one.... on the FreeBSD you can install it:

    # pkg install intel-ixl-kmod

It requires to add `if_ixl_updated_load="YES"` into /boot/loader.conf.local and reboot as the module can only be loaded at boot time. The port version is at 1.12.2 currently.


Cheers,
Franco

**Comment by alteredtech** [comment]
Okay so I have given that a shot and nothing. I have now installed windows server 2019 and no luck there native but I am trying a few of the drivers on intels website. So far 2 have not worked.
