### ISSUE TITLE
AMD axgbe network driver / software VLAN support

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/src#113]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

When using the AMD axgbe driver, it seems that VLAN's only work when hardware vlan tagging is enabled. The short term work around could be to leave the defaults for the card (which enables hwvlan tagging), although that doesn't play well with certain cards in combination with netmap (IPS).

If we dump some inbound packets without hwvlan tagging enabled, it looks like packets are being double tagged with a prefix vlan 0.

```
# tcpdump -e -ni ax0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ax0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:28:52.742659 xxxxx > xxxxxx, ethertype 802.1Q (0x8100), length 223: vlan 0, p 0, ethertype 802.1Q, vlan 5, p 0, ethertype IPv4, xxxxx.20067 >xxxx.5043: UDP, length 173
17:28:52.813376 xxxxx > xxxx, ethertype 802.1Q (0x8100), length 302: vlan 0, p 0, ethertype 802.1Q, vlan 5, p 0, ethertype IPv4, xxxx.50499 > xxxx.5043: UDP, length 252
```

**To Reproduce**

Disable VLAN hardware tagging (Interfaces -> Settings -> VLAN Hardware Filtering), reboot  and create a VLAN on the `axX` interface, the vlan itself won't receive any traffic, when inspecting the parent you will notice the additional vlan tag.

**Expected behavior**

Not seeing the additional `vlan 0`  on inbound packets :)

**Describe alternatives you considered**

none

**Screenshots**

none

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.1.4 (amd64, OpenSSL).

**Comment by swhite2** [comment]
Even though the driver is correctly disabling the hw VLAN tag/strip offloading, it seems a firmware issue is causing the card to append an extra VLAN tag to incoming packets (VLAN 0). Note that even though Q-in-Q is supported in the card, it is not enabled by default and as such it doesn't seem to be a part of the problem.

I'm proposing to simply keep it enabled for now. Please see #115

**Comment by fichtner** [comment]
Nice work, thanks. I suppose this is relevant for 21.1.6?

**Comment by swhite2** [comment]
The sooner the better :) 

Before we proceed though, I just realized there might in fact be a code issue here.

**Comment by swhite2** [comment]
Woops, it might not even be firmware-related at all.. just tested out a working scenario without permanently enabling the hw filtering. I'll create a new PR. Sorry!

**Comment by swhite2** [comment]
See #116

**Comment by fichtner** [comment]
Second patch looks neat, ship in 21.1.6 and close? :)

**Comment by swhite2** [comment]
> Second patch looks neat, ship in 21.1.6 and close? :)

Fine by me :)

**Comment by fichtner** [comment]
Ok, added to 21.1.6 queue. Thanks!

**Comment by fichtner** [comment]
For testing:

    # opnsense-update -zbkr 21.7.a_69
    # opnsense-shell reboot
