### ISSUE TITLE
e1000: add driver support for Intel I219-LV

### ISSUE THREAD

**Issue by rakaur** [opnsense/src#117]
The recent addition of I219V is absolutely fantastic. However, I'm sitting over here with several boxes full of I219-LMs! Joke's on me!

Anyway, how about some driver support, homies?

https://bsd-hardware.info/?id=pci:8086-0d4c-1028-09a6

Edit: Ah, that's LM, not LV. Fixed.

**Comment by fichtner** [comment]
Disruptive comments in https://github.com/opnsense/src/issues/110#issuecomment-826369178 so I close and lock it.

As said previously said the timeline for inclusion is 21.7. https://github.com/opnsense/src/issues/110#issuecomment-823522889
