### ISSUE TITLE
IPsec traffic stalling on 20.7

### ISSUE THREAD

**Issue by fraenki** [opnsense/src#118]
**Describe the bug**
After upgrading from 20.1.4 to 20.7.2 IPsec phase 2 tunnels will randomly stall (IKEv1, mode tunnel IPv4). Only restarting strongswan seems to fix this issue (temporarely).

Several other people have reported the same issue on 20.7. More reports, details, hardware specs, etc. are available in the forums:
https://forum.opnsense.org/index.php?topic=18918.0

**To Reproduce**
1. Establish an IPsec tunnel between two physical OPNsense 20.7 boxes
2. It was better reproducable with IKEv2 (at least in my case)
3. Send enough traffic through the tunnel (200-400 MB in my case)
4. The tunnel completely stalls, no traffic gets through

Downgrading to OPNsense 20.1 immediately fixes this issue (according to other reporters in the forum).

However, @mimugmail tried to reproduce this issue on OPNsense virtual machines, but did not succeed unfortunately. So this issue is _probably_ related to specific vendors/hardware or drivers. Until now all reporters were using Intel NICs.

**Expected behavior**
Traffic should get through the IPsec tunnel, it should not stall after transferring a specific amount of data.

**Relevant log files**
When using IKEv2 strongswan is actually able to detect the problem and restart the SA after a while:

```
Sep  8 17:03:05 charon[62985]: 05[IKE] <con5|1> giving up after 10 path probings
Sep  8 17:03:05 charon[62985]: 05[IKE] <con5|1> restarting CHILD_SA con5 
```

Note that with IKEv1 strongswan will still think that the tunnel is active and alive, so with IKEv1 you need to restart strongswan.
Of course, in both cases this does not really help, because the tunnel will get stuck again after very little traffic.

**Additional context**
I've manually built packages for strongswan 5.8.3 and 5.9.0 and tested them on OPNsense 20.7.2, but this did not change anything.

Other reporters and myself tested several different IPsec settings, but this did not change anything (details of the various settings can be found in the Forum). Changing the options in `Interfaces: Settings` did not help either.

**An interesting observation:** when _one_ box was still running OPNsense 20.1 and only the other box was on OPNsense 20.7, this issue did not occur at all. Only after upgrading _both_ boxes to 20.7 we first experienced this issue. Also this issue does not IPsec connections between OPNsense and other firewalls – those are 100% stable. Only OPNsense-to-OPNsense connections are affected.

**Environment**
My setup:
OPNsense 20.7.2 / 20.7.3 (amd64, OpenSSL).
Supermicro A2SDi-2C-HLN4F (Intel C3338 CPU, Intel C3000 NIC)

Other reporters:
Landitec scope7-1510 (Intel Atom C3558)
Supermicro A2SDi-4C-HLN4F (almost the same as mine)

**Comment by fichtner** [comment]
Most likely 7b9fade9157d -- test kernels soon.

**Comment by fraenki** [comment]
@fichtner thanks for tracking this :+1:

**Comment by fichtner** [comment]
Test snapshot:

    # opnsense-update -zbkr 21.7.a_69
    # opnsense-shell reboot

**Comment by rudiservo** [comment]
this also happens between OpnSense and an EdgeRouter-X, it was pretty difficult to find the culprit since ER-X has a ipsec offload issue has well...

**Comment by fichtner** [comment]
It would be helpful if someone commented on the test kernel. Ideally we can push it to 21.2.6, but not without feedback.

**Comment by fraenki** [comment]
I cannot perform this test on the affected remote location so easily. However, I plan to visit this location within 1-3 months and may use this opportunity to test/verify the fix.

But that's several months away, so if someone could test earlier that would be awesome.

**Comment by rudiservo** [comment]
I can perform the test, just need to know if I can roll back and how to do it.

**Comment by fichtner** [comment]
You can revert kernel and base from the firmware packages tab by reinstalling the package. Or use:

    # opnsense-update -bk
    # opnsense-shell reboot

**Comment by fichtner** [comment]
Ok, after more radio silence for likely valid reasons 21.1.6 will not fix this. We will probably just roll this into 21.7.


Cheers,
Franco

**Comment by rudiservo** [comment]
@fichtner yes sorry, emergencies at work, forgot about this. testing it now.

**Comment by rudiservo** [comment]
@fichtner updated the kernel with
#opnsense-update -zbkr 21.7.a_69

rebooted
changed in Miscellaneous, hadrware accelleration to AES-NI Cpu based
rebooted

Doing and rsync to a NAS for backup almost 3GB in and has not stalled yet.

**Comment by fichtner** [comment]
@rudiservo thanks, that sounds great. Can you ping again in a day if something changes or if it’s still looking good. Much appreciated for possibility of 21.1.6 inclusion. ❤️

**Comment by rudiservo** [comment]
@fichtner sure, I am transfering over a TB of data, so far so good since yesterday.
Again sorry for the radio silence it was not intentional and I forgot to add a task reminder for it. Thanks for giving me the heads up.
BTW I have a AMD Ryzen 3400U, I do not know if that changes anything?

**Comment by fichtner** [comment]
No worries, dealing with some issues here as well so not a lot of time either. ;(

Basically the bug happens when context switches are happening and AESNI is used by multiple programs or streams so either fast data transfers or slow machines in general. If you could reproduce before not seeing stalls is as good as sign as it gets.


Cheers,
Franco

**Comment by rudiservo** [comment]
Tested it up until now with a high amount of traffic, concurrent connections and multiple vpns at the same time, no issues whatsoever.

Reverted back to old kernel, rebooted, started an rsync and the vpn froze after a couple of minutes.
The changes to the code do seem to make sense, it is now accounting for the hmac block variability, on my end it was stable with no issues and nothing unusual showed up in the logs.

Good job!

**Comment by fichtner** [comment]
Ok, perfect. I will add to 21.1.6 then. Thanks a ton to your testing and FreeBSD for fixing this. ❤️
