### ISSUE TITLE
Backport "iflib" from HardenedBSD/FreeBSD 13 to remove network performance bottleneck

### ISSUE THREAD

**Issue by somova** [opnsense/src#119]
Switching to the "iflib Network Interface Driver Framework" has introduced a bug into the network stack which throttles network throughput. This bug also affects Opnsense version 20.7 and later. Analyses revealed an improper handling of TX interrupts, so that the network stalls.

The issue and solution have already been described by the FreeBSD community:

https://reviews.freebsd.org/D27683
https://reviews.freebsd.org/R10:81be655266fac2b333e25f386f32c9bcd17f523d

It would be great to backport the fix to the current Opnsense version to get pback to the regular network performance.

**Comment by joshland** [comment]
This is a little above my paygrade to manage this patch - but, I think that I am affected by the same issue.  I am getting terrible performance, on download.

**Comment by shahraj** [comment]
@fichtner To clarify are you suggesting moving to 13 ahead of 22.1 or waiting until 22.1 for this fix.

I'm not wild about the idea losing so much performance and having to wait to Jan2022 for the fix. My gig tx speeds are cut down to ~625mbps from this.

**Comment by fichtner** [comment]
I’m not wild about the idea that rushing this on somebody else’s time isn’t the solution either given past experiences with iflib.

To be blunt, changing a core network component on the premise of performance without factoring in regression testing, potential issues, release schedule I have no idea where you think you can make this work earlier at no cost?

**Comment by shahraj** [comment]
I'm not suggesting rushing anything or moving to 13 earlier than scheduled- I agree that would not be a good idea without thorough testing. This is well beyond my skill and pay grade, so I just wanted to get your thoughts on it.

If I have to live with degrade performance til then, so be it.

**Comment by somova** [comment]
In my eyes stability is more important than performance. Of course, I wish go get back the performance before iflib was introduced. But, in case a temporary fix or quickly implemented backport will have unknown side effects or impact on stability, we should wait for FreeBSD 13 or an official backport to HBSD 12.x.

Btw: Fortunately, I identified a second performance degradation in my system caused by the power management. After a reconfiguration the NIC performance increased from 15 MB/s to 40 MB/s (out of 100 MB/s). So, for the next six months the reduced performance is manageable.

**Comment by erickufrin** [comment]
+1 .... seeing 1Gb+ internet circuit constrained to ~625Mb

Same hardware was able to achieve 950Mb on older versions of opnsense.

**Comment by AdSchellevis** [comment]
and anyone bothered to try disabling meltdown and spectre mitigations?  (https://docs.opnsense.org/troubleshooting/hardening.html#spectre-and-meltdown)

**Comment by erickufrin** [comment]
I tested disabling meltdown and spectre mitigation it didnt make a difference for me.

Im wondering if I change hardware can I avoid this issue...or at very least throw more CPU at the problem make it go away? Or is it bound to the specific NIC's?

**Comment by fichtner** [comment]
81be655266f is on the unofficial branch for 22.1 now so it will be part of any future 22.1 release and release candidate.
