### ISSUE TITLE
Driver for Intel I219-V

### ISSUE THREAD

**Issue by Hoerli1337** [opnsense/src#120]
Hello!
I have installed OPNsense 21.1.5 using the following system:
- Intel Core i5-10500T
- GIGABYTE B460M DS3H V2
- 8GB RAM (2x4GB)

The built-in LAN controller is an Intel I219-V, which is not recognized.
I've read a few forum posts that, for one, as of OPNsense 18.X, the driver has been added (?!) and it should actually run.
Others have compiled the driver themselves.

What is the current easiest way to get the LAN adapter to run?

A Dell (Intel) X550-T2 network card was recognized without problems.

**Comment by fichtner** [comment]
I219-V is a class of devices. As of 21.7 all devices known to FreeBSD 12-STABLE are supported.

**Comment by Hoerli1337** [comment]
Apparently something does not fit from the driver.
I have installed the following:
OPNsense 21.1.5-amd64
FreeBDS 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

@mimugmail I'm not sure if you noticed and if this is the appropriate driver, 
but I have only Intel I219-V and not "I219 V10".

@fichtner where do I get the latest 21.7? Per dev repository I do not get a newer version yet.

**Comment by fichtner** [comment]
@Hoerli1337 You can try to install this dev kernel https://github.com/opnsense/src/issues/118#issuecomment-841759026

**Comment by Hoerli1337** [comment]
OPNsense 21.7.a_384-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

Even with the latest kernel, the interface is not recognized.

**Comment by fichtner** [comment]
Did you get the snapshot kernel? Using development version also uses production kernel. Can confirm with uname -a

**Comment by Hoerli1337** [comment]
The specification of the kernel fits so far.
After the update I also did a reboot, so that everything is taken over.

```
FreeBSD OPNsense.lan 12.1-RELEASE-p16-HBSD FreeBSD 12.1-RELEASE-p16-HBSD #0  b531d3958f5(stable/21.1)-dirty: Tue Apr 20 11:00:08 CEST 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64
root@OPNsense:~ # opnsense-update -bk
Your system is up to date.
```

Have had a lot to do with FreeBSD, unfortunately. Do I still have to do a kernel update here and if so how?

**Comment by fichtner** [comment]
So sorry, copied the wrong response. This is the actual snapshot:

https://github.com/opnsense/src/issues/118#issuecomment-831888495

**Comment by Hoerli1337** [comment]
Great now it works. The interface is now recognized cleanly and I can manage it.

**Comment by fichtner** [comment]
Cool, you can lock the kernel from the firmware GUI packages tab to prevent removal on update and then upgrade seamlessly into 21.7 when it becomes available with the driver included. :)

Close ticket?

**Comment by Hoerli1337** [comment]
Perfect!
Ticket can be closed :)
