### ISSUE TITLE
Loading firmware (driver) not distributed with Freebsd

### ISSUE THREAD

**Issue by Techknowledgeman** [opnsense/src#122]
Hi, I am using an Intel 7260 mpci wifi card, and the intel drivers it requires is not distributed with bsd as it has licensing limits. The package is available and can be loaded via fw_update. I am at a loss as to how this is done in opnsense though since this tool is missing and there's no packages for it,
I can't build my own port because they are prebuilt packages, and I assume the same Intel licensing issue/closed source code.

How can I load the driver to have this wifi card work?

**Comment by fichtner** [comment]
Closing due to FreeBSD version change in 22.1
