### ISSUE TITLE
VLAN priority / Class of Service in PF

### ISSUE THREAD

**Issue by djGrrr** [opnsense/src#13]
Is it possible to bring in a pf patch from FreeBSD?
https://svnweb.freebsd.org/base?view=revision&revision=301998
https://github.com/freebsd/freebsd/commit/b06d3a64e7ac5d5033eced5e6cc06e9fc2371915

This would bring in functionality that pfSense had with it's custom patches, but with an official patch.

It appears that set-tos in scrub rules alone is not enough to support google fiber's full upload speeds; even though ToS is somewhat backwards compatible with CoS, the ToS is put inside the tagged vlan packets, whereas CoS is in the ethernet frame itself, outside the tagged vlan, and therefor is only compatible with CoS when using the native (untagged) vlan.

**Comment by fichtner** [comment]
I'm not against testing this given that it can be backported easily, but I want to refrain from early inclusion from now on as we've been hit by multiple regressions in the past weeks, which we can avoid by not merging changes, even the ones that are going to be included in FreeBSD 10.4.

**Comment by fichtner** [comment]
@djGrrr This is actually included in releng/11.0, so it'll be in 17.1.
