### ISSUE TITLE
CARP issues on IPv6 only interface using VMXNET3 interfaces.

### ISSUE THREAD

**Issue by norrland** [opnsense/src#139]
I'm running two virtual instances of OPNsense 21.7.5 in VMware ESXi, 7.0.1, build 17325551.

Each machine has 3 vmxnet3 interfaces and one e1000 interface. 
* vmx0 -> wan (dvSwitch1)
* vmx1 -> lan (dvSwitch2)
* vmx2 -> opt1 "VIPTEST" (dvSwitch3)
* em0 -> opt2 "placeholder" (dvSwitch3)

dvSwitches has MacLearn enabled rather than promiscuous mode. [MacLearn](https://williamlam.com/2018/04/native-mac-learning-in-vsphere-6-7-removes-the-need-for-promiscuous-mode-for-nested-esxi.html)

One CARP (v6) VIP setup on interface "VIPTEST". VIP: 2001:db8:aaaa:aaaa::1234/64
VIPTEST: Static IPv6:
- vm1: 2001:db8:aaaa:aaaa::1/64
- vm2: 2001:db8:aaaa:aaaa::2/64

When assigning "VIPTEST" to the vmx2 interface on both VMs, CARP works for about 8minutes +- 20sec, before the BACKUP machine stops receiving the multicast packets. This leading to the BACKUP logging:
`2021-11-25T13:32:00 | kernel | carp: 1@vmx2: BACKUP -> MASTER (master timed out)`

When instead assigning "VIPTEST" to em0 on both VMs, I see no issues at all.
I have tested this on multiple VMware vSphere hosts, and even with the VMs on the same physical host. Without any change.
I have tested this on older OPNsense releases, 21.1-3 IIRC, seeing the same behaviour.

Please let me know if there are any additional information I could provide.
The closest upstream related issues I've come across is regarding too many VMXNET3 interfaces, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198406

**Comment by norrland** [comment]
After some further testing I've found that the timeouts occur when the Backup VM has the VMXNET3 interfaces.

**Comment by fichtner** [comment]
Closing stale issue.
