### ISSUE TITLE
Able to use multiple PCI buses other than pci0:0:*:*: (I have devices on pci0:1:*:*: pci0:2:*:*: pci0:3:*:*: that do not show in pciconf)

### ISSUE THREAD

**Issue by mailinglists35** [opnsense/src#140]
**Important notices**

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

I don't see interfaces Realtek NIC (`chip=0x816810ec`) and Broadcom WiFi (`chip=0x435314e4`) in `pciconf -lv`

**Describe the solution you like**

I believe the cause could be the opnsense kernel only sees `pci0:0:*:*:` and ignores `pci0:1:*:*` and others 

**Describe alternatives you considered**

I can see the nics when booting https://download.freebsd.org/ftp/releases/VM-IMAGES/12.2-RELEASE/amd64/Latest/

**Additional context**

difference between what freebsd sees and what opnsense sees, apparently opnsense it misses two other devices as well, the KVM memory ballon and the virtio console, each of them **not** on `pci0:0:*:*` address

````
$ diff pciconf.opnsense.txt pciconf.freebsd.txt 
75a76,92
> none1@pci0:2:0:0:	class=0x078000 card=0x11001af4 chip=0x10431af4 rev=0x01 hdr=0x00
>     vendor     = 'Red Hat, Inc.'
>     device     = 'Virtio console'
>     class      = simple comms
> none2@pci0:3:0:0:	class=0x00ff00 card=0x11001af4 chip=0x10451af4 rev=0x01 hdr=0x00
>     vendor     = 'Red Hat, Inc.'
>     device     = 'Virtio memory balloon'
>     class      = old
> re0@pci0:4:0:0:	class=0x020000 card=0x012310ec chip=0x816810ec rev=0x06 hdr=0x00
>     vendor     = 'Realtek Semiconductor Co., Ltd.'
>     device     = 'RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller'
>     class      = network
>     subclass   = ethernet
> bwn_pci0@pci0:5:0:0:	class=0x028000 card=0x04d814e4 chip=0x435314e4 rev=0x01 hdr=0x00
>     vendor     = 'Broadcom Inc. and subsidiaries'
>     device     = 'BCM43224 802.11a/b/g/n'
>     class      = network
````

**Comment by mailinglists35** [comment]
> If it works in FreeBSD 13 it will be in OPNsense 22.1.

It works on FreeBSD 12.2 (see my link of the FreeBSD image I've tested)

**Comment by AdSchellevis** [comment]
so, you can try our beta which is based on FreeBSD 13..... (https://forum.opnsense.org/index.php?topic=25535.0)

**Comment by mailinglists35** [comment]
the beta does see all the pci buses and devices. thanks.
