### ISSUE TITLE
UEFI - installation media hangs when booting on Chromebox, might need FreeBSD 14 patches to boot

### ISSUE THREAD

**Issue by TrevorScheitrum** [opnsense/src#146]
Hello,

I have a system that is a converted chromebox, and its running Mr. Chromebox's UEFI firmware and bios.  I believe this is a problem with FreeBSD that opnsense is based on, as pfsense fails to boot in the same way, as does FreeBSD 13.0, but FreeBSD 14.0 boots cleanly and is usable, I'm also able to boot the windows 10 UEFI installer, and Ubuntu 21.10 UEFI installer as well.  I wrote the Opnsense 21.7.1 amd64 vga (and also tried dvd) installer to a 16gb usb 3.0 stick, (also tried an 8B usb 2.0 usb stick and different usb ports), and booting in UEFI mode hangs the system after

Booting...
EFI framebuffer information:
addr, size          0xc0000000, 0x10000000
dimensions          800 x 600
stride              832
masks               0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000
_
screenshot taken from someone else's post experiencing same problem:  https://i.imgur.com/bJQgqo5.png

It seems to be an issue with FreeBSD, found this issue on FreeBSD bug tracker: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209821

Hoping the issue gets figured out and merged into opnsense's base soon!
Thanks!

**Comment by fichtner** [comment]
@TrevorScheitrum can you try our 22.1.r1 https://pkg.opnsense.org/releases/22.1/ as we have an almost recent 13-STABLE in there

**Comment by TrevorScheitrum** [comment]
@fichtner opnsense 22.1-RC1 booted and installed, thank you!

**Comment by fichtner** [comment]
Yay great 😊
