### ISSUE TITLE
[BUG] NIC Watchdog timer on RTL8111/8168/8411, subvendor=0x1458

### ISSUE THREAD

**Issue by NightDragon1** [opnsense/src#155]
**Describe the bug**

Since the Update to OPNSense 22.0 I have troubles with the onBoard-NIC. In this version there had been buffer issues on the NIC using zenarmor, so I had to disable it. Since the update to 22.1 it becomes worse by getting regularly watchdog messages (without the use of zenarmor) about the NIC, causing the interface to get down and up in a loop, until it stops working. 

In total there are four cards, 3x PCI, 1xon-Board - all are identified as RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller's.
The difference between the onBoard-Card and the other three PICe-Card is the subtype:
PICe Cards: vendor=0x10ec device=0x8168 **subvendor=0x10ec** subdevice=0x8168
on-Board Card: vendor=0x10ec device=0x8168 **subvendor=0x1458** subdevice=0xe000

*To Reproduce**
Simple  use the described NIC above in OPNSense 22.1 as active interface for WAN or LAN.

**Expected behavior**

No watchdog issue

**Describe alternatives you considered**

It seems like it's a known issue in BSD:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=166724#c13

A solution might be the following:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=166724#c96

**Environment**

Software version used and hardware type if relevant, e.g.:
  OPNsense 22.1.1_1-amd64
  FreeBSD 13.0-STABLE
  OpenSSL 1.1.1m 14 Dec 2021

**Comment by aronmal** [comment]
I guess my problem https://github.com/opnsense/core/issues/5602 could be the same. So take information from my my issue if this one has the **incomplete** tag. But [NightDragon1](https://github.com/NightDragon1) already seem to have suggested a solution. I'm not into FreeBSD and therefore sadly can't help more than reporting this issue too.

**Comment by fichtner** [comment]
Have you installed os-realtek-re? It’s in the release notes after all.

**Comment by NightDragon1** [comment]
I'm going to check that soon

**Comment by NightDragon1** [comment]
@aronmal Could you check what types of card you got, by running `devinfo -rv | grep 0x10ec` on your system?

**Comment by aronmal** [comment]
```
root@SecondaryFw:~ # devinfo -rv | greo 0x10ec
          hdacc0 pnpinfo vendor=0x10ec device=0x0283 revision=0x00 stepping=0x03 at cad=0
          re0 pnpinfo vendor=0x10ec device=0x8168 subvendor=0x1462 subdevice=0xb171 class=020000 at slot=0 function=0 dbsf=pcie0:6:0:0 handle=\_SB_.PCI0.RP06.PXSX
root@SecondaryFw:~ # 
```

**Comment by aronmal** [comment]
> Have you installed os-realtek-re? It’s in the release notes after all.

Solved it! speed test with full 1Gb/s running without a problem. Thanks! But great it's a known and "fixed" issue. Great work OPNsense Team!!!

**Comment by gramster** [comment]
I used to have this problem too, but it would happen every few weeks. I have just come back from a 2 week vacation and updated the firewall, and now it is happening every few minutes. I searched for this and found this posting, so tried installing os-realtek-re but it has not fixed the problem.

Hardware: https://www.amazon.com/gp/product/B08DFL2BM2/

**Comment by roadbikemike** [comment]
I am having a similar issue with the RTL8111 using a PC Engines apu1d4 board.  Worked great with pfSense, but OPNsense has been nothing but problems.  In my case, the NIC does not go down, but appears to be causing frequent system crashes.  I did install os-realtek-re which seemed to help, but there are still crashes.  This morning the system crashed, then would not boot.  Comes up at the db prompt so guessing this is a fresh install.  Super frustrating...

**Comment by fichtner** [comment]
Driver support issue. Nothing we can do.

**Comment by JRGonz** [comment]
I know this is an old report but I’m not sure if the earlier posters noticed that modifications to /boot/loader.conf had to be made. I just installed the plugin since I’m having the same problem and added it to loader.conf and will report later if I have further issues. The notes appear during the pkg install and may be missed. The install doesn’t do this automatically.

**Comment by roadbikemike** [comment]
I should have made an update to my original post, but my specific issue was not related to the NIC but the PC Engines apu1d4 power supply going out.  Appears the PSU was not providing enough voltage to the system so I would get random crashes.  The suspected issue with the RTL8111 was a red herring and not the source of the issue.  Replaced the PSU, problem has not returned.
