### ISSUE TITLE
Feature Request: Support TPM devices and use it as an additional entropy source

### ISSUE THREAD

**Issue by jeolives** [opnsense/src#159]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Description**

I'd like to propose adding support for Trusted Platform Modules (TPM) by default. Currently, a custom kernel must be compiled to enable the device.

TPM support has been available in FreeBSD since 2011 with the 8.2-RELEASE [1]. Additional support for the updated TPM 2.0 specification was added in 2018 [2].

Whilst upstream FreeBSD also does not enable support for the device by default - various other embedded device distributions already make it easily accessible with a packaged kmod install or a config line change such as in OpenWrt [3] or Raspberry Pi OS [4]

In FreeBSD and OPNsense, support for TPMs is added during a kernel compile through editing a config file residing in `./src/sys/amd64/conf/` either `GENERIC` or `MINIMAL`:

```
device tpm
```

Though, it can be argued that it should be kept disabled as its main feature, secure boot, does not yet have the infrastructure in FreeBSD (and thus OPNsense). However, this hardware is becoming more and more prevalent and will be sitting idle. 

But, a lack of secure boot is also the case in a lot of Linux distributions - but has not stopped them from enabling it. For now, the TPM is leveraged as an additional source of good quality entropy [5]. 

This has also become available to FreeBSD as an option in 2019, and has been in FreeBSD since 12.1 [6].

In can be enabled in FreeBSD/OPNsense by adding the following line in the same config as where the line, `device tpm` resides:
```
options TPM_HARVEST
```

The above config options were tested on a PCengines apu2e4 with an Infineon SLB 9665TT2.0 without any adverse effects on 22. I do not have any other devices/appliances to test this on.

Size wise, it does not have a major effect on the compiled image. 

[1] https://www.freebsd.org/cgi/man.cgi?query=tpm
[2] https://reviews.freebsd.org/D18048
[3] https://github.com/openwrt/openwrt/commit/3fcc4b656aeafc30221927806e9a3f641b9377f3
[4] https://www.infineon.com/dgdl/Infineon-OPTIGA_SLx_9670_TPM_2.0_Pi_4-ApplicationNotes-v07_19-EN.pdf?fileId=5546d4626c1f3dc3016c3d19f43972eb
[5] https://github.com/openwrt/openwrt/blob/26e7c2275730486a5a1201fbafe72ccdac15f6e4/target/linux/generic/config-5.15#L2421
[6] https://www.freebsd.org/status/report-2019-01-2019-03.html#FreeBSD-boot-security-improvements

**Comment by AdSchellevis** [comment]
Are you sure you can't enable tpm support using a loader parameter (or `kldload tpm` for that matter)?

```
tpm_load="YES"
```

Should do the trick according to the man page (the module itself seems to be on disk). The `TPM_HARVEST` option probably isn't set, but would induce less risk for others when used as a module.

**Comment by jeolives** [comment]
Thanks for clarifying that. I've just started getting into BSD coming in from the Linux and didn't fully understand that it is already compiled as a module (but not loaded). I thought that I needed to compile it first with  `device tpm` and then load it. I didn't really trust the man page either since it hasn't been updated to show that TPM2.0 support is available and that other chips besides the one listed (e.g. Infineon 9665) is also supported. 

`tpm_load=YES` via the GUI > Settings > Tunables also reports that it can be loaded.

```
root@[redacted]~ # dmesg | grep tpm
tpmtis0: <Trusted Platform Module 2.0, FIFO mode> port 0xc31-0xc32 iomem 0xfed40000-0xfed44fff on acpi0
```

Glad to know it is similar to `dt-overlay` in Linux, and with the benefit of an even simpler syntax on FreeBSD.

However, one would still need to compile a custom kernel for `TPM_HARVEST` since it is a compile time option isn't it? Even if the flag is enabled for FreeBSD/OPNsense, this would only affect users if: 

1. A user loads the TPM kernel module via `loader.conf`, knowing that it is an unlisted tunable and;
2. The device is a TPM2.0 device;

as the only files affected by the flag would be `/sys/dev/tpm/tpm20.h` and `/sys/dev/tpm/tpm20.c` [1]. As I see it, it's a bit odd that the flag is not turned on by default in the config, since it enables additional functionality. Though, the Linux equivalent is also not turned on by default. However, the documentation there still recommends that it be compiled in when setting up the config [2]. Can you point me to a mailing list or active discussions page to query why it isn't supported by default upstream in the `GENERIC` config? 

I guess in the meantime, I can just continue compiling a custom kernel to support `TPM_HARVEST`.

[1] https://reviews.freebsd.org/D19620
[2] https://cateee.net/lkddb/web-lkddb/HW_RANDOM_TPM.html

**Comment by AdSchellevis** [comment]
You would indeed still have to set `TPM_HARVEST` manually in your build, we prefer to wait for `GENERIC` to include that setting at the moment as the state isn't fully clear to us. You can always check upstream (FreeBSD) why there is an optional parameter which isn't set by default.  https://bugs.freebsd.org/bugzilla/ and https://forums.freebsd.org/ might be good places to start your journey.

**Comment by jeolives** [comment]
Thank you, @AdSchellevis!

**Comment by lilianmoraru** [comment]
Surprised to see that TPM is not enabled.
I was just reading the "Transparent Proxy" documentation and there seems to be a worry that somebody can steal the private key and dove through settings, to tell it to keep it inside TPM, it seems it's not supported.
In `System` -> `Trust` -> `Certificates` would be nice to have the setting `Save on this firewall (TPM)` as the default for `Private key location`, if the hardware supports it - in that case, you don't have to worry about the firewall being compromised remotely and the private key being stolen, just to make sure it's not physically stolen, which would technically "give access" to the private key.
