### ISSUE TITLE
Contribution guidelines out of date?

### ISSUE THREAD

**Issue by macpijan** [opnsense/src#160]
Hello,

According to the guidelines: https://github.com/opnsense/src/blob/sandbox/22.1/CONTRIBUTING.md#pull-requests
we should open PR to the `master` branch. But such branch does not exist anymore. I can see in the PR history,
it's been there a few months ago. Should we target the default branch now (sandbox/22.1)? Can this be clarified
in the document? Thanks.

**Comment by AdSchellevis** [comment]
the contributing guidelines are imported from core, src is a downstream repository which usually doesn't qualify for PR's, let me correct this in the guidelines and close this ticket.
