### ISSUE TITLE
Ifconfig -v does not display DDM of SFP+ GBIC

### ISSUE THREAD

**Issue by bueste** [opnsense/src#162]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Opnsense DEC3850: ifconfig -v (for example) ax0 does not display the DDM.

**To Reproduce**

1. Go to the terminal
2. ifconfig -v ax0
3. It should display the DDM of the GBIC. In my part Flexoptix GBIC. On pfsense it display the DDM

**Expected behavior**
On pfsense it should be correct:
![image](https://user-images.githubusercontent.com/10118288/164307883-5b604178-c832-4fc8-9a22-9f49a73bc638.png)

With the newest opnsense business version not:
![image](https://user-images.githubusercontent.com/10118288/164307615-021d2379-03b5-44f1-b8d7-2a7d47318ec8.png)

OPNsense 21.10.3-amd64
FreeBSD 12.1-RELEASE-p22-HBSD
OpenSSL 1.1.1m 14 Dec 2021
DEC3850

**Comment by AdSchellevis** [comment]
output depends on the driver, AMD's axgbe doesn't seem to support sfp attributes in ifconfig (the data that is available would be presented in dmesg by the way)

**Comment by bueste** [comment]
No the DDM is not in dmesg, only tranceiver data:
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP
ax0: Link is DOWN
ax0: xgbe_config_sph_mode: SPH disabled in channel 0
ax0: xgbe_config_sph_mode: SPH disabled in channel 1
ax0: xgbe_config_sph_mode: SPH disabled in channel 2
ax0: xgbe_config_sph_mode: SPH disabled in channel 3
ax0: xgbe_config_sph_mode: SPH disabled in channel 4
ax0: xgbe_config_sph_mode: SPH disabled in channel 5
ax0: xgbe_config_sph_mode: SPH disabled in channel 6
ax0: xgbe_config_sph_mode: SPH disabled in channel 7
ax0: RSS Enabled
ax0: Receive checksum offload Disabled
ax0: VLAN filtering Disabled
ax0: VLAN Stripping Disabled
ax0: Checking GPIO expander validity
ax0: SFP detected:
ax0:   vendor:   FLEXOPTIX
ax0:   part number:    S.B1312.10.XDL
ax0:   revision level: A
ax0:   serial number:  F78YFDX
ax0: link state changed to DOWN
ax0: Link is UP - 1Gbps/Full - flow control off
ax0: link state changed to UP

**Comment by AdSchellevis** [comment]
the ax driver doesn't offer DDM information, only static module information. Not even sure if AMD offers this on other platforms to be honest. Marking this upstream as the driver isn't ours.

**Comment by svengrun** [comment]
Looks like it is linked to [https://github.com/opnsense/src/issues/178](url)

axgbe does support this fully on Linux. Tested on the DEC850 with Debian 11.

**Comment by swhite2** [comment]
Fixed in https://github.com/opnsense/src/commit/9774ff2354a9834ef64e09e9b5fa981a23949ee2

**Comment by melroy89** [comment]
> Fixed in [9774ff2](https://github.com/opnsense/src/commit/9774ff2354a9834ef64e09e9b5fa981a23949ee2)

Thank you!
