### ISSUE TITLE
OPNsense DVD installer is painfully slow

### ISSUE THREAD

**Issue by sorenstoutner** [opnsense/src#167]
The OPNsense DVD installer in painfully slow.  This is an issue that has existed for a while, and was recently confirmed when installing 22.1.2 from a DVD.

The problem appears to be that some background task is performing massive random reads from the DVD during the boot and installation process, which causes the available bandwidth for the intended activties to be restricted.

A recent install took almost two hours.  As a comparison, installing pfSense from DVD takes only a few minutes.

**Comment by fichtner** [comment]
Closing stale issue.

**Comment by sorenstoutner** [comment]
Was this closed because it was fixed?

**Comment by fichtner** [comment]
It's never been slow for me and I've never heard substantial and frequent reports about it. "painfully slow" is also not a useful problem description and I'm assuming a bit of support may fix it. But I don't have community time for this.

**Comment by sorenstoutner** [comment]
If you read the full text of the bug report, you will see that painfully slow is defined as 2 hours vs. the expected 5 minutes.  I have consistently replicated this problem more than a dozen times.  Have you ever tried installing from a DVD?

**Comment by fichtner** [comment]
Yes, I think you fail to see the point that the time definition is not the actual lack of information given WRT HW or VM setup, used drives, connectors, server hardware, burning method etc etc

**Comment by sorenstoutner** [comment]
What information would you like to troubleshoot this problem?

I have experienced this issue on a number of burned medium (usually created with K3B).  The medium itself does not appear to be the issue and the files can be access and copied off of them rapidly.  It is only when the OPNsense installer is running that there are problems.

All of the installations were done on bare metal hardware.  No virtual machines were involved.

Various different DVD drives were used.  All with the same symptoms.

If there is any other information I could provide that would be helpful I would be more than happy to provide it.  But generally, my experience is that if you take the ISO and burn it to any DVD medium and use it to do an install on any physical hardware you should be able to replicate the problem.
