### ISSUE TITLE
Support for Sierra Wireless EM7565 (LTE Modem)

### ISSUE THREAD

**Issue by NKnusperer** [opnsense/src#169]
FreeBSD added support for a bunch of new LTE cards, including the EM7565:
https://cgit.freebsd.org/src/commit/?id=89d98b9b003e63dfdf182fa3144a3e809019fcd4
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263700#c13

Can we get this into OPNsense?
Related forum post: https://forum.opnsense.org/index.php?topic=30688.msg147983

**Comment by fichtner** [comment]
See https://github.com/opnsense/src/commit/a72dccaa7d6ce which should be released with 22.7.7
