### ISSUE TITLE
Add support for HPET on newer AMD CPUs

### ISSUE THREAD

**Issue by Kishi85** [opnsense/src#170]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

On newer AMD CPUs HPET a reduced number of HPET Timers is presented by the CPU allocating only a 512-byte MIMO window instead of the as far required 1k window which makes HPET unavailable on Systems with such a CPU.

**To Reproduce**

1. Boot on a System with a newer AMD CPU (e.g. EPYC-Rome)
2. HPET driver is unavailable due to:
```
hpet0: <High Precision Event Timer> iomem 0xfed00000-0xfed001ff on acpi0
hpet0: memory region width 512 too small
device_attach: hpet0 attach returned 6
```

**Expected behavior**

HPET should be allowed load with a reduced MIMO window matching the number of timers present.

**Solution**
This is already fixed in upstream FreeBSD stable/13: https://cgit.freebsd.org/src/commit/?id=972ea9cc57fd9c13c118dab0d8797e6716fdc171
Bugreport: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=262638

Please apply the patch from upsteam to allow HPET timers to be used with OPNsense on newer AMD CPUs.

**Additional context**
This will drastically increase the precision of the NTP server clock especially and is therefore highly desired.

**Environment**
OPNsense 22.7.8-amd64
FreeBSD 13.1-RELEASE-p3
AMD EPYC 7F32 8-Core Processor

**Comment by fichtner** [comment]
84eef8761f35 -- requires a bit of safety testing, but if all goes well this will be included in 22.7.9

Thanks for the report!
