### ISSUE TITLE
WAN disconnecting arbitrarily

### ISSUE THREAD

**Issue by hyperboly** [opnsense/src#175]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

The WAN interface has been dropping randomly lately. The interface under "Interfaces" > "[WAN]" will show that it is disconnected in the webUI. This is fixed with a reboot (tried reloading the interface, did not work).

Working versions: 22.X.X.
Broken versions: 23.X.X. 

**To Reproduce**

1. Update OPNsense to 23.1
2. Wait a couple of days
3. WAN interface disconnects
4. Reboot and wait a few more days
5. WAN interface disconnects
6. Repeat from step 4

**Expected behavior**

OPNsense does not drop WAN connection every couple of days

**Describe alternatives you considered**

I have had this problem since updating to 23.1 and was hoping for an update that fixes this problem, but so far I am still getting the problem. This happens once every few days (weekly maybe?) so I have not been able to reproduce it well because I do not know the source of the problem, sorry.

**Screenshots**

Logs:
![image](https://cdn.discordapp.com/attachments/907301880252747787/1093081511680561222/image.png)
Image shows 3 mins before reboot and after reboot. Reboot occurred after 15:33:41, system came back up at 15:36:XX.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.5_4-amd64
Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (2 cores, 4 threads)
RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller

Any help is appreciated and any additional information needed will be provided, thanks.

**Comment by fichtner** [comment]
Closing old support issue. If someone wants to step in feel free.
