### ISSUE TITLE
Marvel 88E1512 phy support

### ISSUE THREAD

**Issue by dimitrijp** [opnsense/src#176]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

I would like to utilize Compulab Fittlet3 SBC, but unfortunate they moved from Intel to Marvell controllers.
Currently Marvel 88E1512 phy is not supported by default in freeBSD 13.1, and therefore not detected under OPNSense.
There is what looks like driver for 88E1512 in freeBSD 14 branch available.
Opening this issue, to check if would be possible to incorporate driver into OPNSense.

https://cgit.freebsd.org/src/commit/?id=adff82ea35b77a2961376f0806794698d97ed018

**Expected behavior**

Merge the driver for testnig from freeBSD 14 branch.

**Describe alternatives you considered**

Wait for OpnSense to migrate to freeBSD 14 branch :)

**Environment**
Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.6 (amd64, OpenSSL).
Fitlet3
Marvel 88E1512 phy

**Comment by fichtner** [comment]
I'm happy to pick up stable/13 commits, but I haven't seen it / no MFC after annotation in commit.

We don't plan to move to FreeBSD 14 before 14.1 (mind you 14.0 isn't even out yet). 23.7 will possibly be based on FreeBSD 13.2 so perhaps we are there in time for 24.7 if it doesn't shift schedules.

**Comment by fichtner** [comment]
Timeout on upstream issue.
