### ISSUE TITLE
USB Ethernet Link toggles between up and down repeatedly

### ISSUE THREAD

**Issue by hackwin** [opnsense/src#180]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

USB Ethernet adapters are not working properly.  I tried 3 different brand adapters.  One USB 2.0 and two USB 3.0.
I swapped switches and network cables to make sure they are working.  This issue does not occur on FreeBSD v13.1, v13.2, or Windows 10 Pro.

The message appears as:
```
ue0: link state changed to DOWN
ue0: link state changed to UP
ue0: link state changed to DOWN
ue0: link state changed to UP
ue0: link state changed to DOWN
ue0: link state changed to UP
```
It toggles every half a second.  Maybe a race condition with a semaphore?

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Plug in USB ethernet (to host and to router/switch)
2. Install OPNSense in a virtual machine (USB pass-through) or hardware PC
3. Wait until the system boots up

**Expected behavior**

Link should be stable and not have error messages.

**Describe alternatives you considered**

Upgrade OPNsense to FreeBSD v13.2 ?

**Screenshots**

https://i.ibb.co/0ZT1wFT/vmplayer-X16-PWp-AUx-P.gif

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

Happened in both virtual machine and physical hardware.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1 (amd64, OpenSSL).
USB Ethernet cards tested:  
Realtek USB 10/100/1000
ASIX AX88179

USB ethernet is important because it allows laptops and mini-PCs to be used as routers when PCI slots are not available.

**Comment by hackwin** [comment]
I also tested pfSense Community Edition and it did not have the same bug.  USB Ethernet adapter worked normally.

**Comment by evasil** [comment]
I can confirm the issue persists on two Intel NUCs (D2820 and D5450) with OPNSense versions 22.7 and 23.1

**Comment by haroldskie** [comment]
has this issue been fixed?

**Comment by fichtner** [comment]
USB devices will disconnect for any reason at no particular time. This can't be fixed.


Cheers,
Franco

**Comment by hackwin** [comment]
Works normally in FreeBSD and pfsense

**Comment by fichtner** [comment]
Close then? 😉

TBH I still don’t see any real world data of the cause, just the kernel end result.

**Comment by cjangrist** [comment]
This prevents using opnsense on any system with only 1 nic. As before, pfsense does not have this issue (was trying to move away from them...)

**Comment by fichtner** [comment]
It does not and using a two NIC appliance is more useful than a single NIC one is better than a zero NIC one. That’s just a fact. 😊

**Comment by e-e-eric** [comment]
Sounds like this it may be this [upstream issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252165).

OPNsense under Hyper-V with USB ethernet works, I ran it for a few years like this (home environment). I don't know about other hypervisors, but Linux kernels should work too.

m.2*PCIe ethernet for mini-PCs may also work. Probably want to go with [Intel over Realtek](https://forums.truenas.com/t/is-my-realtek-ethernet-really-that-bad/1496). However, a new mini-pc with dual ethernet off Aliexpress might end up being the better value proposition.
