### ISSUE TITLE
Random increase of mac_stats.checksum_errs on ixgbe

### ISSUE THREAD

**Issue by taihun3995** [opnsense/src#191]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

Errors in counts increase randomly on netstat when using onboard Intel X552/X557, confirmed that they are checksum errors.

**To Reproduce**

Errors in counts will increase at random time while the interface is in use.

**Expected behavior**

This bug was reported and fixed earlier this year in upstream, and should give it a look to backport:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222979
https://github.com/freebsd/freebsd-src/commit/8de48df35c3bf4800176b7aa54c75a01864d458b

**Describe alternatives you considered**

None

**Screenshots**

None

**Relevant log files**

None

**Additional context**

None

**Environment**

OPNsense 23.7.9 (amd64)
Supermicro X10SDV-4C-TLN2F

**Comment by fichtner** [comment]
Suppose we will add this to 24.7.
