### ISSUE TITLE
Port forwarding with policy routing broken

### ISSUE THREAD

**Issue by djGrrr** [opnsense/src#20]
As referenced in these forum threads:
https://forum.opnsense.org/index.php?topic=4512.0
https://forum.opnsense.org/index.php?topic=4516.0

I realized after reading these threads that my own port forwarding is also not working for my policy based routes. sysctl net.pf.share_forward=0 does restore it to working order.

After doing some testing with tcpdump, I realized that the issue is actually another NAT related problem. The "return" packets are not being NATed (the source address is from my LAN network on the external interface). I believe that the routing table, instead of the reply-to route, is being used to determine the translation address, since connecting from the external interfaces subnet does NAT the return packets properly.

**Comment by BlackDragon381** [comment]
I think it's the same problem:
https://forum.opnsense.org/index.php?topic=4517.0

**Comment by fichtner** [comment]
Should be fixed... https://github.com/opnsense/src/commit/716683127
