### ISSUE TITLE
page fault panic in sfxge(4) at MSI-X

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/src#228]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at  https://github.com/opnsense/src/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/src/issues?q=is%3Aissue

**Describe the bug**

Kernel panic in 24.7 when loading `sfxge(4)`; previously #173
Notably, this did NOT occur with 23.x.

**To Reproduce**

1. Obtain an SFN85xx adapter (model doesn't matter)
2. kldload sfxge
3. panic()

**Expected behavior**

Not panic()

**Describe alternatives you considered**

N/A; multiple cards tested including in both Legacy and UEFI modes

**Screenshots**
N/A

**Relevant log files**

Separate due to size of ddb.

**Additional context**

Did not reproduce in 23.x at any point. I believe this is likely a different issue from the one previously addressed in #173

Further details to follow pending more testing.

**Environment**

stable/24.7-n267758-4ad7ad40bc77
HP 800G2 SFF
Tested with SFN8522, SFN8522M, SFN8522-PLUS, SFN8542 in both Legacy and UEFI modes

**Comment by fichtner** [comment]
The stack trace would be useful although I can see there was absolutely no movement for sfxge(4) on FreBSD stable/14 and just a single TCP related commit on main. One upstream bug here, not sure if related https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259155

**Comment by fichtner** [comment]
We could also run a debug kernel to get the vmcore if you want. It would really help narrow down the issue.

**Comment by fichtner** [comment]
@rootwyrm did not compile but this looks fishy 6c68c771c88 -- can you pick it up from here or do you want a test kernel to install?

**Comment by rootwyrm** [comment]
@fichtner exactly what I found as well, which is why it's a headscratcher. I also got it to reproduce in 13.4-RELEASE, so I must have the wrong bifurcation point or it's something else. 

```
sfxge0: <Solarflare SFC9200 family> port 0x3000-0x30ff mem 0xd1000000-0xd17fffff
,0xd2000000-0xd2003fff at device 0.0 on pci1
sfxge0: Using MSI-X interrupts


Fatal trap 12: page fault while in kernel mode
cpuid = 1; apic id = 02
fault virtual address   = 0x0
fault code              = supervisor read instruction, page not present
instruction pointer     = 0x20:0x0
stack pointer           = 0x28:0xfffffe00c3f7f4c8
frame pointer           = 0x28:0xfffffe00c3f7f4f0
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 43157 (kldload)
rdi: fffff80108b31800 rsi: fffffe00c3f7f540 rdx: fffffe00d99fc230
rcx: 00000000c0306938  r8: 0000000000000000  r9: 0000000000000000
rax: 0000000000000000 rbx: fffffe00c3f7f540 rbp: fffffe00c3f7f4f0
r10: fffff80108569800 r11: fffff800017f8000 r12: 0000000000008802
r13: fffff80108569810 r14: fffffe00d99fc230 r15: 0000000000000000
trap number             = 12
cpuid = 1
time = 1732906923
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe00c3f7f1b0
vpanic() at vpanic+0x131/frame 0xfffffe00c3f7f2e0
panic() at panic+0x43/frame 0xfffffe00c3f7f340
trap_fatal() at trap_fatal+0x40b/frame 0xfffffe00c3f7f3a0
trap_pfault() at trap_pfault+0x46/frame 0xfffffe00c3f7f3f0
calltrap() at calltrap+0x8/frame 0xfffffe00c3f7f3f0
--- trap 0xc, rip = 0, rsp = 0xfffffe00c3f7f4c8, rbp = 0xfffffe00c3f7f4f0 ---
??() at 0/frame 0xfffffe00c3f7f4f0
dump_iface() at dump_iface+0x145/frame 0xfffffe00c3f7f5a0
rtnl_handle_ifevent() at rtnl_handle_ifevent+0xa9/frame 0xfffffe00c3f7f620
if_attach_internal() at if_attach_internal+0x3df/frame 0xfffffe00c3f7f670
ether_ifattach() at ether_ifattach+0x2c/frame 0xfffffe00c3f7f6b0
sfxge_attach() at sfxge_attach+0x8d4/frame 0xfffffe00c3f7f930
device_attach() at device_attach+0x3ac/frame 0xfffffe00c3f7f980
device_probe_and_attach() at device_probe_and_attach+0x41/frame 0xfffffe00c3f7f9
b0
pci_driver_added() at pci_driver_added+0xf2/frame 0xfffffe00c3f7f9f0
devclass_driver_added() at devclass_driver_added+0x29/frame 0xfffffe00c3f7fa20
devclass_add_driver() at devclass_add_driver+0x11e/frame 0xfffffe00c3f7fa60
module_register_init() at module_register_init+0x85/frame 0xfffffe00c3f7fa90
linker_load_module() at linker_load_module+0xb81/frame 0xfffffe00c3f7fd80
kern_kldload() at kern_kldload+0x164/frame 0xfffffe00c3f7fdd0
sys_kldload() at sys_kldload+0x5c/frame 0xfffffe00c3f7fe00
amd64_syscall() at amd64_syscall+0x100/frame 0xfffffe00c3f7ff30
fast_syscall_common() at fast_syscall_common+0xf8/frame 0xfffffe00c3f7ff30
--- syscall (304, FreeBSD ELF64, kldload), rip = 0x62043f404da, rsp = 0x62043412
d18, rbp = 0x62043413290 ---
KDB: enter: panic
```

Relevant flow portion is:
`device_probe_and_attach()` (OK) -> `device_attach()` (OK) -> `sfxge_attach()` (OK) -> `ether_ifattach()` (OK) -> `if_attach_internal()` (OK) -> `rtnl_handle_if_event` (??) -> `dump_iface` (panic) with null MAC

**Comment by fichtner** [comment]
> dump_iface() at dump_iface+0x145/frame 0xfffffe00c3f7f5a0

ah yes you will find the patch should work then (if it compiles ;)

**Comment by rootwyrm** [comment]
@fichtner if you can send over a test kernel, that would be best. I don't have my building system available and won't for a while still. I'm also poking at PF/VF and SRIOV, but no behavior changes with any of those.

**Comment by fichtner** [comment]
Just for fun have a look at that stack trace ;) https://github.com/opnsense/src/issues/224

**Comment by rootwyrm** [comment]
> Just for fun have a look at that stack trace ;) #224

Ding ding ding, **we have a winner!** That's exactly it (and also nicely shows why I was poking at PF/VF.) ;) It's definitely, definitely that. 

I SUSPECT that what's going on is the new netlink stuff is probably racing PF/VF resulting in a NULL mac addr being passed up (the actual cause of the panic.) Especially since sfxge used to have a specific NULL check around that. (And hopefully the newer firmware isn't also a problem.)

Let me know where I can grab the test kernel and I'll validate. (I cooked up some scripts to quick modify PF/VF.)

**Comment by fichtner** [comment]
# opnsense-update -zkr 24.7.8-sfxge

Good luck :)

**Comment by rootwyrm** [comment]
Can I get a direct URL for the pkg? (Yeeeeep, no sfxge, no connectivity on this one. :( )

**Comment by fichtner** [comment]
Sure:

     https://pkg.opnsense.org/FreeBSD:14:amd64/snapshots/sets/kernel-24.7.8-sfxge-amd64.txz

**Comment by fichtner** [comment]
> I SUSPECT that what's going on is the new netlink stuff is probably racing PF/VF resulting in a NULL mac addr being passed up (the actual cause of the panic.)

It's a generic issue that becomes more and more apparent but I am unsure why it's easier to observe in OPNsense and not in FreeBSD 14. Here's another one that hasn't gained much traction. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277849

**Comment by rootwyrm** [comment]
> > I SUSPECT that what's going on is the new netlink stuff is probably racing PF/VF resulting in a NULL mac addr being passed up (the actual cause of the panic.)
> 
> It's a generic issue that becomes more and more apparent but I am unsure why it's easier to observe in OPNsense and not in FreeBSD 14. Here's another one that hasn't gained much traction. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277849

Honestly, my guess is the default OPNsense tuning versus -RELEASE tuning. Something in the sysctl's causing just enough sensitivity increase - possibly to the point of a race - but I'm not sure what. If my antiquated memory is right (it probably isn't,) it would probably be somewhere in net.link.ether.

But hey! Check _this_ out.
```
root@egw0:~ # uname -a
FreeBSD egw0.XX.rootwyrm.XX 14.1-RELEASE-p6 FreeBSD 14.1-RELEASE-p6 sfxge_fix-n267972-6c68c771c88 SMP amd64
root@egw0:~ # ifconfig sfxge0
sfxge0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=ec07ab<RXCSUM,TXCSUM,VLAN_MTU,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6,HWSTATS>
        ether 00:0f:53:XX:XX:XX
        media: Ethernet autoselect
        status: no carrier
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
root@egw0:~ # sysctl hw.sfxge.tx_ring hw.sfxge.rx_ring
hw.sfxge.tx_ring: 1024
hw.sfxge.rx_ring: 1024
```

Now I just need to confirm with turning SRIOV + VF back on; if this wasn't the problem, that will _definitely_ break it again.

**Comment by rootwyrm** [comment]
👍 
Everything checking out on both the 800G2, and just for giggles, tried the Really Nasty Secret Box. (`num_vfs: 128` - and not as passthrough.) RNSB did the same panic on 14.2-RC1. But both worked perfectly with this fix.

Worth trying to get push this upstream as late 14.2 errata maybe?

**Comment by fichtner** [comment]
I have no faith in the RE path at the moment but I will make sure this gets to stable/14 at least.

**Comment by fichtner** [comment]
Thanks, pushed to stable/24.7 on our end. Will make upstream review next week, but closing now.

Cheers,
Franco

**Comment by fichtner** [comment]
Here we go https://github.com/freebsd/freebsd-src/pull/1537 ✈️

**Comment by rootwyrm** [comment]
Thanks very much @fichtner!
