### ISSUE TITLE
[BUG] Offloading error

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/src#23]
Even if offloading is disabled The checksums on my APU1 seem to be wrong (according to the output of tcpdump) this leads to dropped packets (no packets get out of my network). The device has already been rebooted and I also tried setting it manually via ifconfig but it does not work - so the driver is broken. Can I switch to another kernel with the old driver by installing it via scp (firmware update page or pkg update will not work)

CC @farma12

**Comment by fichtner** [comment]
Can't do much here, sorry.
