### ISSUE TITLE
Layer2 scanner needed in tools

### ISSUE THREAD

**Issue by peppelinux** [opnsense/src#26]
Hi,
Yes, this is not a real issue, sorry for this :)
I'm asking if is it possible to have netdiscover, or arpscan, into OPNsense, it could be helpfull in Interfaces/Diagnostic tools to see what IP is available in a LAN.

I do not have any preferences if netdiscover or arpscan even if i use netdiscover frequently, arpscan is good enough.

I can also develop it by myself and then ask you a pull request, here in github, first I need to know if this feature is needed by others users.

It could be great having also a generic arpping and a arpwatch process, if possibile :)
These could alert when ip collisions happens.

let me know if interested,
bye

**Comment by AdSchellevis** [comment]
@peppelinux it's no problem to open a feature request, but you probably better open this issue in our plugins repository, src is meant for kernel/base (FreeBSD) issues, core for our standard system on top of it and plugins are meant to extend the system.

**Comment by fabianfrz** [comment]
this should be two tickets:

- tools: request the package
- plugins: request the frontend code
