### ISSUE TITLE
[deprecated] net.inet.ip.fastforwarding

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/src#27]
Hi,
as stated here [https://svnweb.freebsd.org/base?view=revision&revision=r290383](https://svnweb.freebsd.org/base?view=revision&revision=r290383)
the sysctl option for fast forwarding has been removed quite a while ago...

Cheers,

Stephan

**Comment by fichtner** [comment]
Wrong repo, but I'll mop this up. Thanks!
