### ISSUE TITLE
pax_segvguard_lookup messages

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/src#36]
Hey @lattera, 

On my vm (osx Parallels) I seem to have quite some of the following messages:

```
[585147] [HBSD SEGVGUARD] pax_segvguard_lookup:419 stat error. Bailing.
[585147]  -> pid: 44680 ppid: 1 p_pax: 0xa50<SEGVGUARD,ASLR,NOSHLIBRANDOM,NODISALLOWMAP32BIT> 
```

FreeBSD OPNsense.localdomain 11.2-RELEASE-p6-HBSD FreeBSD 11.2-RELEASE-p6-HBSD  5d1a9cafe(master)-dirty  amd64

I didn't notice any other odd behaviour.

Best regards,

Ad

**Comment by lattera** [comment]
I'll take a look soon at what could cause this error.

**Comment by AdSchellevis** [comment]
thanks!

**Comment by AdSchellevis** [comment]
@lattera A bit of extra information, the pid related to the message seems to belong to 

```
/usr/local/bin/python2.7 /usr/local/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py start
```

Which is a background script for captive portal (this might be consistent over other installs as well)

**Comment by lattera** [comment]
Is the process crashing? Or is it completing successfully?

**Comment by AdSchellevis** [comment]
it doesn't appear to be crashing, it stays active, but keeps spawning a lot of these messages on the console.

**Comment by lattera** [comment]
Can you apply the attached patch and let me know the output the next time the error occurs?

[2019-01-18_segvguard_debug-01.patch.txt](https://github.com/opnsense/src/files/2774148/2019-01-18_segvguard_debug-01.patch.txt)

**Comment by AdSchellevis** [comment]
ok, build and installed the kernel, I'll let you know when the error reappears.

**Comment by AdSchellevis** [comment]
@lattera just noticed the same on my box, here's the output:
```
[HBSD SEGVGUARD] pax_segvguard_lookup:421 stat error (9). Bailing.
 -> pid: 26653 ppid: 1 p_pax: 0xa50<SEGVGUARD,ASLR,NOSHLIBRANDOM,NODISALLOWMAP32BIT> 
```

**Comment by lattera** [comment]
Thanks! So the `(9)` is the errno value, which translates to `EBADF` (bad file descriptor). I wonder if the file descriptor is closed by the time `pax_segvguard_lookup` is called in this particular edge case. I'll dig in a little bit deeper later this week or next. There could be a small race condition. In this case, the race would be harmless, but it's still a bug.

**Comment by AdSchellevis** [comment]
maybe it would be good to add this patch to the standard kernel, always good to know why it's throwing an error :) Just let me know if there's something else I need to test, it seems to hit quite often, but haven't seen it error directly after boot.

**Comment by lattera** [comment]
The patch posted above would provide a bit of an information leak to attackers, potentially leaking them info into the state of SEGVGUARD. I wouldn't want it in production.

**Comment by AdSchellevis** [comment]
I see, thanks for the clarification!

**Comment by lattera** [comment]
Ideally, this error message in its entirety might be best suited for verbose boot mode. The same argument about leaking state could be applied to the error message even without the patch applied. I'll discuss it with Oliver soon and report back.

**Comment by AdSchellevis** [comment]
@lattera any news on this? I still see pax_segvguard_lookup() messages for some services on our latest kernel and just wondered.

**Comment by michelvankessel** [comment]
hey guys. I have to same message with ntopng 3.8 

2020-05-09T20:44:12   kernel: pid 99966 (ntopng), uid 288: exited on signal 11
2020-05-09T20:40:31   kernel: -> pid: 99966 ppid: 1 p_pax: 0xa50<SEGVGUARD,ASLR,NOSHLIBRANDOM,NODISALLOWMAP32BIT>
2020-05-09T20:40:31   kernel: [HBSD SEGVGUARD] [ntopng (99966)] Suspension expired.
