### ISSUE TITLE
IPv6 policy routing not working

### ISSUE THREAD

**Issue by patrick7** [opnsense/src#39]
I created an IPv6 firewall rule using a gateway (GIF, WireGuard). The rule matches but traffic is sent to the default gateway (netstat -6rn)

**To Reproduce**
1. Create an IPv6 firewall rule using a default gateway
2. Test it

**Expected behavior**
Routing over the gateway which is specified in the rule

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 19.1.6 (amd64, OpenSSL).
AMD APU, KVM VM, ..

Also see https://forum.opnsense.org/index.php?topic=10846.0, https://forum.opnsense.org/index.php?topic=11988.msg57209

**Comment by fichtner** [comment]
same as #38
