### ISSUE TITLE
opnsense VPN IPSec bug site-to-site tunnel on the same subnet

### ISSUE THREAD

**Issue by acastano59** [opnsense/src#4]
I am trying to open a VPN IPSec tunnel between an Opnsense and another VPN IPSec capable server (freebsd). If both equipements are on differents subnets, it works like a charme. But, if both equipements are on the same subnet, when the Opnsense is the initiator I cannot mount up the tunnel.

I try to explain you the issue:

A) Mounting the tunnel

[     192.168.0.0/24        ] [        192.168.1.0/24         ]
[opnsense] <-----------> [router] <-------------> [VPN serveur]

It works.

B)  Mounting the tunnel

[      192.168.0.0/24       ]
[opnsense] <--> [VPN serveur]

It doesn't work if the opnsense is the initiatior.

Taking dumps I can see that the packets MAC destination address is the Opnsense gateway. It is not correct, because both equipments are on the same subnet so the MAC destination address of the packet must be the MAC of the equipement and not the gateway's MAC.

Coud you confirme the problem? If I remember well, I think that the same problem is present on Pfsense.

Do not hesitate to ask me more questions about the problem. I couldn't give you configurations or dumps because of the security context.

Alejandro

**Comment by acastano59** [comment]
this has been fixed on:
Pfsense, version:
2.2-RELEASE (amd64)
built on Thu Jan 22 14:03:54 CST 2015
FreeBSD mifirewall.localdomain 10.1-RELEASE-p4 FreeBSD 10.1-RELEASE-p4 #0 36d7dec(releng/10.1)-dirty: Thu Jan 22 15:12:35 CST 2015 root@pfsense-22-amd64-builder:/usr/obj.amd64/usr/pfSensesrc/src/sys/pfSense_SMP.10 amd64

**Comment by fichtner** [comment]
Reported fixed via email. Thanks.
