### ISSUE TITLE
[HBSD SEGVGUARD] in /usr/sbin/arp

### ISSUE THREAD

**Issue by Melantrix** [opnsense/src#41]
I have random crashes in OPNSense. At the time of the crash i have no internet, no DHCP, no DNS (all which work via the router, DHCP and Unbound). if i log in the console i can ping internet however. but not from the lan, and routing doesn't work between lans or to internet. 

I had a hard time finding logs that could give me an insight in what the problem was, but yesterday i had a log message on the console login page which gives me something, and i hope you guys can help me make sense of it and/or point me in the right direction. 

The reason i created a issue here is because i saw there are some more problems with the HBSD SEGVGUARD, so i would like to help troubleshoot, but i need some directions where to look.. 

the message i get is:

[HBSD SEGVGUARD] [/user/sbin/arp (41031) Suspension expires.
-> pid: 41031 ppid: 71889 p_pax: 0xa50<SEGVGUARD,ASLR,NOSHLIBRANDOM,NODISALLOWMAP32BIT>

I would appreciate any help!

**Comment by AdSchellevis** [comment]
Maybe @lattera could share some tips of where to look, if I’m not mistaken, the suspension message is triggered when a process crashes too often, but Shawn’s the expert, we better ask him.

**Comment by lattera** [comment]
What version of OPNsense and is there a core dump somewhere on the filesystem?

**Comment by Melantrix** [comment]
I'm running on the latest version by automatic update, on the 15th i see that i upgraded from 19.7.3 -> 19.7.4_1. I have experienced these bugs on both versions. 

I just logged in saw that i have a detected problem, i do think its unrelated but just to be clear about everything:

PHP Fatal error:  Uncaught Google_IO_Exception: Operation timed out after 100000 milliseconds with 0 bytes received in /usr/local/opnsense/contrib/google-api-php-client/Google/IO/Curl.php:115

I looked for core dumps on the system, but to be honest i have no idea where to look (for). i did find the file arp.core under root and that seems to point to my wireguard plugin but it looks like a binary file so i'm not sure how to investigate the file further. running file on it gave me this:
arp.core: ELF 64-bit LSB core file x86-64, version 1 (FreeBSD), FreeBSD-style, from 'wg0 -a -n'
and running strings arp.core gives me a lot of strings but it's just references to my vlan interfaces so not much of a help. 

is the arp.core the file you are looking for or do i have to look somewhere else? Can you help me with information on how to use the arp.core file? 

i'm not really familiar with opnsense (it's my first install) but i'm okay-ish with using unix, so i can help/investigate further if you point me in the right direction!

**Comment by lattera** [comment]
That arp.core file is the exact file I'm looking for. Do you have a place where you can upload it?

**Comment by Melantrix** [comment]
> That arp.core file is the exact file I'm looking for. Do you have a place where you can upload it?

I have send an email with the download link to your registered email on your github page. i'm not sure what information the core file holds so i'm not comfortable to post the link here out in the open. 

Just for educational purpose, what are you going to do with the file/what tools are you using to analyse it?

**Comment by lattera** [comment]
I'll use probably a mixture of gdb and lldb to inspect the core dump. The only info that could be sensitive in that file could be MAC addresses. That's about it. The arp program is used to resolve IP addresses to MAC addresses and vice-versa. Nothing crazy.

**Comment by Melantrix** [comment]
Okay, I was afraid that maybe public addresses or stuff could be in it, and the strings command wasn't really conclusive so better safe then sorry. 

Thanks anyway, please let me know if you need more info!

**Comment by Melantrix** [comment]
Any update on this issue by any chance?
