### ISSUE TITLE
dtrace does not start

### ISSUE THREAD

**Issue by clebig** [opnsense/src#42]
Hi,

I have found a problem that I could reproduce on our 3 OPNSense firewalls running version OPNsense 19.7.5_5-amd64.

running dtrace -n 'fbt:::entry { @[probefunc] = count(); }' -c 'any command here' results in the following error : "dtrace: invalid probe specifier fbt:::entry { @[probefunc] = count(); }: "/usr/lib/dtrace/io.d", line 45: operator -> cannot be applied to a forward declaration: no struct devstat definition is available"

This is not reproducible in FreeBSD 12.0.

**Comment by AdSchellevis** [comment]
we're using 11.2

**Comment by clebig** [comment]
I confirm dtrace works too in FreeBSD 11.2-RELEASE amd64 and FreeBSD 11.2-RELEASE-p14.

**Comment by fichtner** [comment]
Not sure why it doesn't work. Likely core team will not be looking into this as this is not mission critical.
