### ISSUE TITLE
after 19.7 upgrade VIRTIO NICs not detected anymore

### ISSUE THREAD

**Issue by pmoser1976** [opnsense/src#47]
I run OPNSense on UNRaid VM (Q35) using virtual NICs (VIRTIO).

On 19.1 only Q35-2.6 worked, using other Q35-x.x there were no NICs detected in OPNsense.
So I ran Q35-2.6, everything fine.

Since update to 19.7 there are no NICs detected anymore!! I tried other Q35 versions, also tried a fresh install an a new VM. => 19.1 shows NICs, 19.7 does not find NICs!!

Now I run a Backup on 19.1 again.
![OPNsense19 7](https://user-images.githubusercontent.com/24461961/62057488-0a1ed080-b220-11e9-9918-50e79489d8fd.png)

**Comment by abraha2d** [comment]
I'm having the same issue. Using Proxmox. I just upgraded from 19.7 to 19.7.8, and virtio interfaces are not being detected. However, I'm using the i440fx machine type, not q35.
