### ISSUE TITLE
OPNsense 19.7.8 not detecting virtio NICs

### ISSUE THREAD

**Issue by abraha2d** [opnsense/src#50]
This is a similar issue to #47, but it doesn't seem to be quite the same.

I recently started using OPNsense as a VM. Host runs Proxmox VE 6.1. The VM is set up with the i440fx machine type, not the q35 machine type (one difference from the issue in #47). Both NICs are of the virtio type.

I just upgraded from 19.7 to 19.7.8 (other difference from the issue in #47), and the virtio NICs are no longer being detected. When I switch the NICs to vmxnet3, the interfaces are detected, but CPU usage hits 100% before I can max out a 300 Mbps WAN connection, so not ideal.

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/src/issues/47 ?

**Comment by abraha2d** [comment]
Not sure if it's the same underlying issue, but #47 was an issue with 19.7. I have no problems on 19.7, but am having problems with 19.7.8.

**Comment by abraha2d** [comment]
Update: seems to be a non-issue. Re-added the virtio NICs to the VM, and OPNsense picked them up with no issues. Closing for now.
