### ISSUE TITLE
Kernel freeze if CARP and bridge are used on the same interface

### ISSUE THREAD

**Issue by ednt** [opnsense/src#57]
Hi we ran into a strange situation:

In a working OPNsense master/slave configuration the master suddenly stops working.

No messages, no infos.
So we thought it is a hardware bug and replaced the complete master unit.
Same result.
So we thought it must be the software and we went back from 20.1.3 to 20.1.0, because at this time it was running already 4 weeks without problem.
Same result.

After searching a very long time we found a FreeBSD bug report from 2015 which is still not solved in the latest 12 version:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200319

And yes, we added temporarily a bridge to our old datacenter.

As result:
You can not use a bridge on an interface where you run CARP !

Be aware of that.

**Comment by fichtner** [comment]
This seems relevant, kp is working on it :)

https://lists.freebsd.org/pipermail/freebsd-current/2020-April/075804.html

**Comment by fichtner** [comment]
I was about to merge this, but:

```
commit bfc2b4b25184d3d37161dfdb9811005a4b10a497
Author: kp <kp@FreeBSD.org>
Date:   Sun Jul 26 17:44:03 2020 +0000

    Revert bridge epochification
    
    Revert r363492, r363491, r363430, r363429 and r362650.
    
    The introduction of epoch in the network stack is incomplete in stable/12, and
    there are simply too many limitations to make the bridge epoch code work there.
    
    The final problem is capability configuration of the bridge member interfaces.
    if_bridge needs to enable promiscuous mode, which for certain drivers (e1000
    for example) can sleep. In stable/12 we may not sleep within epoch.
```

https://github.com/freebsd/freebsd/commit/bfc2b4b25184d3d3
