### ISSUE TITLE
OPNsense seems to miss #201695 from FreeBSD

### ISSUE THREAD

**Issue by larseggert** [opnsense/src#60]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199489. Patch in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=201695

**To Reproduce**
Configure an IPv6 port forwarding rule. tcpdump will show that pf alternates between a link local and a global IPv6 address.

**Expected behavior**
Expect to not have the link local address used.

**Comment by fichtner** [comment]
Funny, now I remember we did the review... https://reviews.freebsd.org/D17633

**Comment by fichtner** [comment]
It was added in 20.7.2.

https://github.com/opnsense/changelog/commit/098a6f852b98358a566ddab70f85749da1999e03#diff-9a75b19337b67d18c3c5a76130bc3d3bR43

So far no complaints.
