### ISSUE TITLE
Typo in Copyright header

### ISSUE THREAD

**Issue by x-jokay** [opnsense/src#62]
In multiple files, there is a typo in the copyright header for **AS IS**.

```sh
...
THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES
...
```

**Comment by AdSchellevis** [comment]
@x-jokay the src repository is a downstream repository of HardenedBSD, which is in turn a fork/downstream of FreeBSD. So typo's in their notes (if any) are usually best handled there.

**Comment by x-jokay** [comment]
Good point, will close this issue.
