### ISSUE TITLE
Enable virtio_console driver per default

### ISSUE THREAD

**Issue by flames** [opnsense/src#64]
Please, enable virtio_console kernel module per default
https://www.freebsd.org/cgi/man.cgi?query=virtio_console&sektion=4
https://hardenedbsd.org/article/op/2017-08-01/stable-release-hardenedbsd-stable-11-stable-v10000481
Thank you in advance

**Comment by fichtner** [comment]
No idea what this means. You link to https://github.com/HardenedBSD/hardenedBSD-stable/commit/eaaa8cd970f indirectly which is included in 11.2 which we had for a long time...
