### ISSUE TITLE
bpf(4) on additional loopback interfaces doesn't seem to be functional

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/src#65]
Although not super important, it's quite annoying from time to time. When using `tcpdump` on additional loopback interfaces, there doesn't appear to be any traffic on them (which is not the case). 
The traffic that is handled over the interface, seems to be landing on `lo0` from bpf(4)'s perspective.

The earliest mention of this issue I could find was this https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=112612, some of the code in the report seemed to be in the kernel but the end result appears to be the same still.

**Comment by fichtner** [comment]
@AdSchellevis Is this still relevant? I remember you said this is the way it works?

**Comment by AdSchellevis** [comment]
@fichtner I guess it "works as designed", which is kind of annoying from time to time, you can't capture traffic on additional loopbacks and traffic never leaving the box doesn't pass bpf either if I'm not mistaken. I don't have plans at the moment to further look into this, so let's close it.
