### ISSUE TITLE
Multicast is badly broken on FreeBSD 12.x need to update kernel to fix it

### ISSUE THREAD

**Issue by RyuunoAelia** [opnsense/src#69]
**Describe the bug**
A Kernel Bug create issues with multicast, mainly interfaces never leaving multicast groups.
A bugfix is already present in upstream FreeBSD 12 STABLE  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246629 please include this fix into opnsense kernel.

**To Reproduce**
Use a program that will register to a multicast group (example is igmpproxy), and see that the group is never left.

**Expected behavior**
The multicast group should be left at least when the program is terminated.

**Additional context**
The bug is fixed upstream.

**Environment**
any opnsense version using FreeBSD 12 on any hardware.

**Comment by fichtner** [comment]
There is a test kernel available, but early indication says FreeBSD 12.1 has more issues here.

**Comment by RyuunoAelia** [comment]
Could you point the instruction to use that test kernel? might be less broken than my current situation.

**Comment by fichtner** [comment]
Use this one with the second multicast patch candidate:

    # opnsense-update -kr 20.7-re-mcast
    # opnsense-shell reboot


Cheers,
Franco

**Comment by fichtner** [comment]
Some more references:

https://forum.opnsense.org/index.php?topic=18490.0
https://forum.opnsense.org/index.php?topic=18347.0

**Comment by fichtner** [comment]
Another test kernel because more fixes needed...

    # opnsense-update -kr 20.7-re-mcast2
    # opnsense-shell reboot

**Comment by RyuunoAelia** [comment]
Yep, the second kernel seem to work.

**Comment by fichtner** [comment]
Ok, will issue new kernel in 20.7.1.
