### ISSUE TITLE
Unread notices not fully visible

### ISSUE THREAD

**Issue by MrHappy** [opnsense/src#71]
The pull-down menu at the top with 'Unread notices' does not show the entire message.
The frame goes as far left as to the search-pane, as you can see in the screenshot:
![afbeelding](https://user-images.githubusercontent.com/686360/90783050-1ecc7b80-e2ef-11ea-903d-5e8ad3c5596c.png)

**Comment by AdSchellevis** [comment]
duplicate https://github.com/opnsense/core/issues/4018
