### ISSUE TITLE
IPv6 NAT Interface Address: Second option to use non link-local address

### ISSUE THREAD

**Issue by vlcty** [opnsense/src#73]
**Is your feature request related to a problem? Please describe.**

My OpenVPN provider issues an IPv6 address from the ULA reserved prefix. For example (`fdbf:1d37:bbe0:0:85:9:0:f2`) . I need a NAT rule for that so I can route IPv6 traffic over it. When I select "Interface address" it uses the link local address instead of the ULA.

**Describe the solution you'd like**

I'd like to have a second option like "Interface address (not link local)" which selects the second address on that interface.

**Describe alternatives you've considered**

Another approach would be to use an alias which is updated via a script.

**Comment by fichtner** [comment]
Alright... I added the patch to our master branch https://github.com/opnsense/src/commit/e7c2aea3c47 and will post a test kernel in a bit... :)

**Comment by fichtner** [comment]
# opnsense-update -kr 20.7.1-netmap4
    # opnsense-shell reboot

Let me know how that goes. :)

**Comment by vlcty** [comment]
Works flawless. Many thanks!   
Just a side question: Can I update my pfSense normally or do I need to do another step?

**Comment by fichtner** [comment]
You can lock the kernel package from the GUI to retain the current one. Health audit will complain but that is expected.

Not sure when we will add this to 20.7.x as I suspect side effects for people who want link-local to be used and do so already.

Once you find this in the release notes unlock kernel and install official version instead.

Although I’m closing this if you have more questions just let me know.


Cheers,
Franco
