### ISSUE TITLE
Packetloss with Half-Closed Connections

### ISSUE THREAD

**Issue by Crazyachmed** [opnsense/src#80]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
I investigated an unusually high number of packets hitting my default deny rule. For the most part they had the TCP-FPA flags set. Looking at a trace I did on the box hosting the firewall-VM I looked at some affected connections and the most unusual about them is that the client still sends traffic into a half-closed connection. Two examples:

1) Server sends FIN
2) Client ACKs the FIN
3) Client Sends additional data -> Packet is blocked
4) Client sends FIN -> Packet is blocked
5) Client retransmits FIN a few times -> Packets are blocked

Second case:
1) Server sends FIN
2) Client ACKs packet before FIN
3) Server retransmits FIN
4) Client ACKs the FIN
5) Client sends FIN -> Packet is blocked
6) Client retransmits FIN a few times -> Packets are blocked

Both clients are Android devices talking to the cloud. One connection is IPv4, the other is IPv6. How can I troubleshoot this further? Why don't the packets match the stateful return path?

I've attached some sample PCAPs from to connections.

**To Reproduce**
1) Permit TCP-Traffic from Android Device via regular stateful rule
2) Use Android device for half an hour or so

**Expected behavior**
All packets should be passed by established stateful path, regardles if they are out-of-order or the connection is half-closed

**Environment**
OPNsense 20.7.3-amd64, OpenSSL
Virtualized on Proxmox (qemu/KVM)

[sense-bug.zip](https://github.com/opnsense/core/files/5321571/sense-bug.zip)

**Comment by AdSchellevis** [comment]
Isn't this a problem of the client (android)? It send an ACK in response to the FIN from the server at sequence 4777 and then (after which the session should have been closed?) it handled a retransmit of 4777 after which it keeps trying to close the connection from his end (FIN, ACK seq 4778) (which was already closed)

I haven't seen reports upstream about state issues with pf, which doesn't mean there can't be an issue, but if there is it would be good to describe what it should do based on the respective rfc's (probably https://tools.ietf.org/html/rfc793, https://tools.ietf.org/html/rfc1379).

There are some timeouts described in pf.conf https://www.freebsd.org/cgi/man.cgi?query=pf.conf which may influence how graceful states are handled (search "set timeout"), not all can be configured using the web interface, but you can always edit /tmp/rules.debug manually.

**Comment by kulikov-a** [comment]
https://forum.opnsense.org/index.php?topic=19351.msg89536#msg89536

**Comment by AdSchellevis** [comment]
I don't think so, no (if I'm reading wireshark correctly)

![image](https://user-images.githubusercontent.com/9783985/95000219-315cf480-05bf-11eb-899d-45bd8ea2d3a3.png)

![image](https://user-images.githubusercontent.com/9783985/95000253-74b76300-05bf-11eb-8495-6f20bbcba852.png)

**Comment by AdSchellevis** [comment]
my mistake it seems frame#52 is the ACK for the FIN,ACK in frame#49, which closes the state. the rest of my previous comment remains relevant I guess.

**Comment by kulikov-a** [comment]
thanks! for me it looks like standard 4-way fin handshake. so it should be:
1)ACK-FIN->
2)<-ACK
3)<-FIN-ACK
4)->ACK
but somehow there is a large time interval between 2) and 3) on android. and connection is closed by FIN_WAIT_1 on server side and tcp.closing on pf

**Comment by Crazyachmed** [comment]
I've increased tcp.closing to 3600 and testing now. How can I make this permanent, if needed?

**Comment by AdSchellevis** [comment]
@Crazyachmed at the moment, you can't but if some of these toggles would be practical to offer to the user, just open a ticket using our templates in core explaining which toggle(s) you need to what purpose, and I'll likely add them in the near future. In practice this will probably only cause some log spamming (when default block is enabled)

@kulikov-a if you look at "SEQ/ACK analysis" in Wireshark, it doesn't seem to expect any packet after 52 anymore either.

**Comment by kulikov-a** [comment]
if tcp.closing helps and I understand correctly, you will probably need to FR. there is no template for limits. the filter.inc script reads parameters directly from the config, adds it to .limits file and then load parameters from file to pf
you can also do it on per rule basis, but afaik only tcp.established is present in GUI
BUT you always can try a rule with 'no state' option for your specific android app

**Comment by kulikov-a** [comment]
@AdSchellevis 
sorry, please explain. I do not quite understand what you want to say. i see no sign of this in SEQ/ACK analysis of frame#52 (but its windows, may be some difference in versions?)

**Comment by AdSchellevis** [comment]
@kulikov-a no problem, I'm no expert in Wireshark (just an infrequent user), but if you look at frame 52 (on osx), you'll notice:
![image](https://user-images.githubusercontent.com/9783985/95013262-76287000-063f-11eb-9c65-de9ccf291ce9.png)

frame#53 looks unexpected to me (no "SEQ/ACK analysis" section)
![image](https://user-images.githubusercontent.com/9783985/95013268-817b9b80-063f-11eb-95c9-2fe83f226d75.png)

**Comment by kulikov-a** [comment]
> just an infrequent user
so am i. I think that final FIN ACK  (and first syn packet in conversation) should not contain SEQ/ACK analysis part. 
because this packets is not sent in response to a packet from a partner.
I made a trace of my ssh login\logout connection and it is: first syn and final fin-ack do not conatain analysis part

**Comment by AdSchellevis** [comment]
but I expect your session wasn't dropped, since sequence looks like this (sequence numbers match).
```
[client: FIN,ACK] --> [server]
[server: ACK] --> [client]
[server: FIN, ACK] --> [client]
[client: ACK] --> server
```

This issue's pcap starts the same, but..:
```
[server: FIN,ACK] --> [client]
[client: ACK] --> [server]
```

Then the client seems to be asked to retransmit the first one, which it appears to be doing and tries to send a FIN,ACK in response to the retransmit (in which case the sequence probably doesn't match anymore). One could try to use sloppy-state to avoid checking sequence numbers, I can't easily replicate this on my end, but still have a strong feeling this isn't pf's fault to be honest.

**Comment by kulikov-a** [comment]
> but still have a strong feeling this isn't pf's fault to be honest

yes. and I think so! as I wrote above, for some reason the transition from step 2) (send ack on response to server fin) to step 3) (send fin-ack from androd to server) takes a very long time on android client. 
![time](https://user-images.githubusercontent.com/36099472/95015587-68321980-0656-11eb-8942-e95f96cc536a.PNG)

its Sep 28, 2020 04:00:02.550088000 when client send ack
and its Sep 28, 2020 04:29:01.861963000 when client send fin-ack
changing tcp.closing time is just for testing imho. i do think that this is application issue, not pf\opnsense.

**Comment by AdSchellevis** [comment]
it certainly doesn't hurt to debug and test which options improve the situation, if timeouts help, I personally don't mind exposing (some of) these settings to the enduser an explain in the docs in which cases these are helpful.

**Comment by kulikov-a** [comment]
>  I personally don't mind exposing (some of) these settings to the enduser

or may be some sort of hooks for .conf statements? (this can be very handy for debugging or advanced tune-up)

**Comment by AdSchellevis** [comment]
we can also discuss about that, but since you can't just merge two pf.conf files due to ordering constraints, we have to define which scenario's we will support, I'm also a bit worried about the robustness since a non loadable pf.conf will just revert to the previous (empty) one.

**Comment by kulikov-a** [comment]
I agree (hooks will have to be inserted into each section: macros, options etc). in addition, it is not yet clear whether the guess about timeouts is helpful )

**Comment by Crazyachmed** [comment]
Setting tcp.closing to 1h has reduced the number of packets hitting the default rule. Looking at a couple of connections that still fail I found a half-closed connection that is closed by the Android device after 8:40h (sic!)

Hard-wiring a stateless "Pass TCP-FIN" has only resulted in the servers sending back RSTs, so there is no use to investigating this further (well except finding out which app is responsible).

But: I am still under the impression that half-closed connections are a valid scenario that shouldn't be closed after 60 seconds. So best is to open an issue under /core like AdSchellevis said?

**Comment by Crazyachmed** [comment]
Sorry, default value for tcp.closing is 900 seconds. So I don't have any current need to granualry tweak any session timers. Of course having such an option would be preferable to using the current presets.

**Comment by AdSchellevis** [comment]
> But: I am still under the impression that half-closed connections are a valid scenario that shouldn't be closed after 60 seconds. So best is to open an issue under /core like AdSchellevis said?

I don't think so, no, it would only make sense to open a FR there if we can actually fix something (exposing settings for example). This case really looks like a client issue (out of sequence responses), in which case the firewall (pf) is dropping these packets under the given circumstances for valid reasons.

**Comment by kulikov-a** [comment]
@AdSchellevis 
sorry, why you think that this is out-of-seq respsonses? I still think that this is client application slow finilazing issue? (rising tcp.closing helps if i understand it right). if so, exposing more timeout settings may help in situations like that?

**Comment by AdSchellevis** [comment]
since it seems to answer to a retransmit when it already answered to the original packet (https://github.com/opnsense/src/issues/80#issuecomment-703244427) and Wireshark doesn't seem to expect the packet either (https://github.com/opnsense/src/issues/80#issuecomment-703236943).  

let's just agree to only open a FR if it seems to solve anything, if timeouts help (which I understood didn't, but I might have misunderstood), best experiment and document different scenarios and open an issue in core next. Just don't open an issue "half-closed connections" should be supported, because this doesn't appear to be the issue. (we can't, nor shall we try, to fix client issues)

**Comment by kulikov-a** [comment]
@AdSchellevis 
I do not propose to open a FR (its up to you and @Crazyachmed of course).
I'm just trying to clarify what we see in the trace and what conclusions can be drawn from this.
I dont see any out-of-seq:
[server:someTLS payload]-->[client] - frame48 - no issue
[server: FIN,ACK] --> [client] - frame49 - no issue
[client: ACK to frame48] -->[server] - frame50 - no issue
[server: FIN,ACK retransmit] --> [client] - frame51 - may be some network latency. no issue
[client: ACKtoframe49(fin-ack)] --> [server] - frame52 - no issue
-----29 minutes of nothing ---- - may be an issue
---standrad tcp.closing 900 sec expired--
 |
\/
the client is trying to complete tcp closing but pf already close state
[clientr: FIN, ACK] --> [server]
[server: ACK] --> [client]

> Then the client seems to be asked to retransmit the first one
client does not ask to retransmit. server may decide to retransmit if it does not receive ACK in retransmission timer limit

**Comment by AdSchellevis** [comment]
we seem to be seeing different things in the same pcap (frame#53 is unexpected), I don't think I can clarify it  more than I tried. if someone can think of a workaround with existing (pf) parameters and is able to explain it, just open a ticket in core and we'll discuss the feature, I'm not going spend more time on debugging a pcap of a broken client (not intended to be offensive).

**Comment by kulikov-a** [comment]
ok. we just understand Seq/Ack numbering and fin-handshake differently. (don't see any offence ))
