### ISSUE TITLE
AWS: Routing issues when using Nitro instances

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/src#85]
**Describe the bug**

When using an ec2 nitro system instance (https://aws.amazon.com/ec2/nitro/) packets seem to vanish after being routed to a machine on the cloud.
If the OPNsense tries to ping the test client directly, packets do arrive in a normal fashion.

![image](https://user-images.githubusercontent.com/9783985/98517510-4f78dd00-226e-11eb-8894-b1b7bbe14f98.png)

**Environment**
Software version used and hardware type if relevant.
e.g.:

```
#pciconf -l -v
hostb0@pci0:0:0:0: class=0x060000 card=0x12371d0f chip=0x12378086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '440FX - 82441FX PMC [Natoma]'
    class      = bridge
    subclass   = HOST-PCI
isab0@pci0:0:1:0: class=0x060100 card=0x00000000 chip=0x70008086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371SB PIIX3 ISA [Natoma/Triton II]'
    class      = bridge
    subclass   = PCI-ISA
intsmb0@pci0:0:1:3: class=0x000000 card=0x00000000 chip=0x71138086 rev=0x08 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371AB/EB/MB PIIX4 ACPI'
    class      = old
    subclass   = non-VGA display device
vgapci0@pci0:0:3:0: class=0x030000 card=0x00000000 chip=0x11111d0f rev=0x00 hdr=0x00
    vendor     = 'Amazon.com, Inc.'
    class      = display
    subclass   = VGA
nvme0@pci0:0:4:0: class=0x010802 card=0x00001d0f chip=0x80611d0f rev=0x00 hdr=0x00
    vendor     = 'Amazon.com, Inc.'
    class      = mass storage
    subclass   = NVM
ena0@pci0:0:5:0: class=0x020000 card=0x00000000 chip=0xec201d0f rev=0x00 hdr=0x00
    vendor     = 'Amazon.com, Inc.'
    device     = 'Elastic Network Adapter (ENA)'
    class      = network
    subclass   = ethernet
```

OPNsense 20.7.4 (amd64, OpenSSL).
ec2: t3.medium, c5.large, t3a.medium, m5.large (all Nitro based)

**Comment by sempervictus** [comment]
If Nitro is KVM, and those are virtio instances, this might be related to #135.

**Comment by AdSchellevis** [comment]
it is https://aws.amazon.com/ec2/faqs/

**Comment by sempervictus** [comment]
I'm tracking the weirdness in #135 - so far i'm seeing some cases where traffic is accept locally and some cases where its routed but not both together. Best part is it seems to be a per-NIC issue - i have one with 3 vNICs and two work fine (routing and interface-bound/sourced) while one only works for interface-bound traffic and won't route a thing.

**Comment by AdSchellevis** [comment]
on ec2 I already spend more time on this madness than I would like to. I haven't seen an upstream (FreeBSD) issue while looking into it, so my hopes aren't very high to be honest that FreeBSD 13 is better, but if you can test it when available that would be practical.

**Comment by sempervictus** [comment]
I'll give it a shot, and luckily it doesn't cost us anything - we don't have nitro, but we do have an improved KVM running our private clouds :).
It seems incredibly strange that an OS (FreeBSD) largely used by the public as a networking stack has poor interface to one of the most common network device drivers on which it is run.

**Comment by mj84** [comment]
Hi,
I experienced this exact issue a few weeks ago with a t3.small instance, and suspected that this issue has something to do with AWS's networking stack.
The AWS business support did point me towards this issue and suggested to change to a t2 instance, which didn't work for us, since OPNsense did reorder the network interfaces and t2 provides no serial console, so I had no easy way to change the interface assignments.

However, after reading through this and all the related issues, and found a workaround, by just disabling hardware CRC offload on my OPNsense's LAN interface.

**Comment by AdSchellevis** [comment]
not likely the same issue, hardware checksum offloading is disabled by default on our end https://github.com/opnsense/core/blob/b3e339194382d5ecf32052e6eecb4f1a356556c1/src/etc/config.xml.sample#L246

**Comment by mj84** [comment]
I just started a fresh t3.micro instance in AWS to verify my findings using the OPNsense 21.1.5 AMI.
Out of the box, txcsum offloading is still active on the interface level:
![image](https://user-images.githubusercontent.com/12526366/141493206-e3c4e955-c6c4-4ed3-8c5b-6d6c530e7204.png)

When explicitly disabling hardware CRC on an interface via the GUI, txcsum offloading will also be disabled and connections from my OpenVPN clients are working. As soon as I revert the interface to the default offloading settings, connections are broken again.

**Comment by AdSchellevis** [comment]
@mj84 it looks like we should check our image defaults if it's enabled after a standard install. thanks

**Comment by sempervictus** [comment]
No dice on my end, disabled `Hardware CRC` by checking the `Disable hardware checksum offload` box, and still can't ping an adjacent VM (but can route traffic to it), while it shows up in ARP and its ingress policy permits all traffic from the OPNSense VM itself:
```bash
root@fw00:~ # ping 10.21.14.10
PING 10.21.14.10 (10.21.14.10): 56 data bytes
^C
--- 10.21.14.10 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
root@fw00:~ # arp -an|grep 14.10
? (10.21.14.10) at fa:16:3e:c4:84:ec on vtnet0 expires in 1177 seconds [ethernet]
```

**Comment by fichtner** [comment]
New FreeBSD version being used. I'm closing this until further data appears.
