### ISSUE TITLE
Huge number of packet errors on outgoing traffic when using mlx5en.

### ISSUE THREAD

**Issue by roooxvee** [opnsense/src#87]
Official FreeBSD Mellanox driver causing huge number of packet errors on outgoing traffic when using VLANs.
The errors happens only on high network load.

Details:
- cpu: Intel(R) Xeon(R) CPU E5450 @ 3.00GHz (8 cores)
- network card: Mellanox MT27710 Family [ConnectX-4 Lx] - MT_2420110034
- network card firmware: 14.26.1040
- network card driver: Mellanox Core driver 3.5.2 (September 2019)
- OPNsense version: 20.7.4-amd64 FreeBSD 12.1-RELEASE-p10-HBSD

I loaded the driver with kldload mlx5en.
Loaded modules:
mlx5en.ko
mlx5.ko
mlxfw.ko

The errors on outgoing traffic persist only when using VLANs.
I tried the following:
- no lagg, no vlans - no errors
- no lagg, vlans setup - errors
- lagg setup, vlans setup - errors
- VLAN Hardware Filtering Enabled/Disabled - errors

How do I observe errors?
netstat -idb -I lagg0_vlanID

I also tried the same driver and the same network card on clean installed FreeBSD 12.2 and FreeBSD 13. No such errors has been detected.

It seems, that the problem is related only to OPNsense. Any suggestions?

**Comment by mimugmail** [comment]
Why didn't you test with vanilla 12.1?

**Comment by roooxvee** [comment]
Testing on 12.1 with iperf:
root@fw2:~ # freebsd-version 
12.1-RELEASE

root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1799766     0     0 90781085315  1791926     0  118268128     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1799764     -     - 90755888499  1791920     -   93180776     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 
root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1822816     0     0 91946946311  1814916     0  119785468     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1822814     -     - 91921426795  1814910     -   94376256     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 
root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1839508     0     0 92789934007  1831564     0  120884236     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1839506     -     - 92764180803  1831558     -   95241952     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 
root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1849578     0     0 93298231227  1841598     0  121546480     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1849576     -     - 93272337043  1841592     -   95763720     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 
root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1859647     0     0 93808727893  1851646     0  122209648     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1859645     -     - 93782692743  1851640     -   96286216     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 
root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1868521     0     0 94258098009  1860495     0  122793682     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1868519     -     - 94231938623  1860489     -   96746364     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 
root@fw2:~ # netstat -idb -I lagg0.3080
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll  Drop
lagg0  1500 <Link#9>      24:8a:07:1e:34:96  1876097     0     0 94643852905  1868056     0  123292708     0     0 
lagg0     - 172.16.8.0/24 172.16.8.102       1876095     -     - 94617587455  1868050     -   97139536     -     - 
lagg0     - fe80::%lagg0. fe80::268a:7ff:fe        0     -     -          0        0     -          0     -     - 

No errors detected.

**Comment by swhite2** [comment]
Bit late to the party..

- Did you do the test in a clean FreeBSD 12.1 environment with or without VLANs (or both)? This is a bit unclear from your test case.
- Does dmesg report any errors?
- Is this problem still occurring in 21.1?
- Are you using IPv6?
- Do the errors keep increasing under load or are they fixed?
- Do the errors show up in the OPNsense GUI as well? (e.g. Dashboard -> add widget -> interface statistics -> apply)

**Comment by roooxvee** [comment]
> 
>     * Did you do the test in a clean FreeBSD 12.1 environment with or without VLANs (or both)? This is a bit unclear from your test case. 
Both. In both cases, no errors was detected.
> 
>     * Does dmesg report any errors? 
No
> 
>     * Is this problem still occurring in 21.1? 
I run a few iperf tests couple of minutes ago, errors are still presents in OPNsense 21.1
> 
>     * Are you using IPv6? 
Yes, in production environment, but I run iperf test on IPv4, because I dont have IPv6 in test environment.
> 
>     * Do the errors keep increasing under load or are they fixed? 
More load, more errors.
> 
>     * Do the errors show up in the OPNsense GUI as well? (e.g. Dashboard -> add widget -> interface statistics -> apply)
 Yes i can view errors in interface statistics. The number of errors are the same in interface statistics and in netstat output.

**Comment by fichtner** [comment]
New FreeBSD version is being used by OPNsense. Closing upstream ticket as we do not modify drivers.
