### ISSUE TITLE
LAGG / LACP

### ISSUE THREAD

**Issue by Julien-nl** [opnsense/src#88]
Hi Guys,
i don't know if this the right place to post this, but today i have configured the LACP on the switches to use LAGG on the opnsense.
everything is configured wel however when i connect the cables the box went crazy and shows a lot of those errors on the console

```
interface stopped distributing possible flapping
interface stopped distributing possible flapping
interface stopped distributing possible flapping
interface stopped distributing possible flapping
```

Can you please advise this either a conf error and not a bug?

Thank you

**Comment by AdSchellevis** [comment]
Please use our forum for discussions (https://forum.opnsense.org/). When maturing into an issue (if there is any), best use our  templates in core (https://github.com/opnsense/core/issues/new/choose) to detail the steps to reproduce and fill in all the details. Let's close this for now.
