### ISSUE TITLE
Cherry-pick: 10GbE driver for AMD SoC 

### ISSUE THREAD

**Issue by swhite2** [opnsense/src#93]
I'm opening this issue to track the current state of the 10GbE AMD driver for the EPYC platform. As of now, only the old
version of the hardware is supported in opnsense/src. The base driver is already upstreamed in freebsd-src and can be pulled in:
-  ~~https://github.com/freebsd/freebsd-src/commit/7113afc84c0b68f1e531dbd6d57d024d868d11c0~~ -- **upstream** 
The differential for the base driver:
- ~~https://reviews.freebsd.org/D25793~~

The following differentials can be cherry-picked once they are upstreamed:
- ~~https://reviews.freebsd.org/D27797 -> tunable to disable split-header, necessary for netmap to work right now.~~ -- **upstream**
~~- https://reviews.freebsd.org/D27800 -> the manpage for the driver~~
- ~~A performance patch, increasing performance by 20% (on par with _ixgbe_)~~ -- **upstream**
- ~~A link issue workaround specific to SFP+ modules. --https://github.com/opnsense/src/pull/94/commits/21ec4b0746dda458c7f3bd9bcc70f63791cc39f3. A differential has been opened: https://reviews.freebsd.org/D28193~~ **upstream**

~~If these patches are not upstreamed by the end of this week, I will provide a patch to address all these issues, which we can later revert in order to stay in sync with the freebsd-src repo.~~

**Comment by swhite2** [comment]
See #94

**Comment by fichtner** [comment]
@swhite2 close this now that it's included or keep open to track further improvements?

**Comment by swhite2** [comment]
> @swhite2 close this now that it's included or keep open to track further improvements?

@fichtner I'd like to keep it open a bit longer for both the manpage and the SFP fix. I will open a separate PR for these if you're good with that.

**Comment by swhite2** [comment]
Closing as everything has been pulled in.
