### ISSUE TITLE
netmap: tun support has problems with filtering

### ISSUE THREAD

**Issue by muratbalaban43** [opnsense/src#96]
Current implementation for netmap(4) tun(4) support adds a pseudo ethernet header, src/dst ethernet addresses being all zero'ed. 
This seems to cause problems with hashing in the consumer applications (i.e. Sensei  / Suricata ).

I'll propose a patch to fix this which will simply add a more proper ethernet pseudo header.

Patch coming in. (This got tested by us and a user who reported this).

**Comment by fichtner** [comment]
Thank you! ❤️

**Comment by muratbalaban43** [comment]
Always a pleasure :) And thanks for being so fast!. 

- [ ]
